Feature/isy 501 rename styleguide to bedienkonzept
IsyFact/isyfact-standards pull request #108
Opened 2023-10-16 15:46 UTC by msg-ptavoul

2023-10-19 12:16 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc
> +Dabei integriert er das Bedienkonzept und stellt auf dessen Grundlage wiederverwendbare Widgets bereit.
Revert

2023-10-19 12:21 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc
> +Basis des Bedienkonzepts sind das Bedienkonzept der Bundesregierung und Gestaltungsregeln für Internetauftritte des Bundesverwaltungsamtes.
Das _Bedienkonzept_ beschreibt die Gestaltungsregeln, Lösungsmuster und Workflows für fachliche Abläufe in Benutzeroberflächen.
Ziel des Bedienkonzepts ist es, dass sich Sachbearbeiter möglichst schnell zwischen unterschiedlichen Anwendungen orientieren können.

2023-10-19 12:24 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/referenzarchitektur-it-system/inhalt.adoc
> +Vorgaben zum Layout sind im xref:isy-bedienkonzept:bedienkonzept.adoc[Bedienkonzept] beschrieben.
Vorgaben zur konkreten Bediedung sind im ...

2023-10-19 12:30 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/isyfact-erweiterungen.adoc
> +Der Baustein Bedienkonzept beschreibt die Gestaltung grafischer Oberflächen nach einheitlichen Gesichtspunkten.
3 --> 2
Das Bedienkonzept beschreibt die Gestaltungsregeln, Lösungsmuster und Workflows für fachliche Abläufe in Benutzeroberflächen.
Ziel des Bedienkonzepts ist es, dass sich Sachbearbeiter möglichst schnell zwischen unterschiedlichen Anwendungen orientieren können.

2023-10-19 12:33 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/rahmenbedingungen.adoc
> +== Bedienkonzepte und die Gestaltung von Benutzeroberflächen
Gestaltung von Benutzeroberflächen

2023-10-19 12:37 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/vorstellung/rahmenbedingungen.adoc
> +Die Dokumente der IsyFact verweisen an verschiedenen Stellen auf das Bedienkonzept und dort zu definierende Regeln.
Die Dokumente der IsyFact verweisen an verschiedenen Stellen auf das Bedienkonzept und auf einen Styleguide.
Im Styleguide werden konkrete Normen wie Farbwerte, Schriftart und Logos definiert die visuelle Aspekte betreffen.

2023-10-19 12:39 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/einstieg/partials/Produktkatalog_IsyFact_Produktvorgaben_Bibliotheken_Anwendungsentwicklung_Typescript_Angular_Entwicklung.csv
> +JS Framework;https://nodejs.org/[node.js];16.x (LTS) / 18.x (LTS);1.3.2;verbindlich;;Wird für den Bau des Bedienkonzepts (`isy-style`) benötigt
Revert

2023-10-19 12:41 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
> +*_Zielsetzung des Bedienkonzeptes und Abgrenzung zum Bedienkonzept_*
Revert

2023-10-19 12:44 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/nutzungsvorgaben/nutzungsvorgaben.adoc
> -= Nutzungsvorgaben Styleguide
Delete all files under /nutzungsvorgaben

2023-10-19 12:46 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/methodik/pages/vorlage-systementwurf/inhalt.adoc
> +Es wird jedoch vorausgesetzt, dass ein solches Bedienkonzept für die Organisation, die die IsyFact einsetzt, bereits vorhanden ist und verwendet werden kann.
Revert

2023-10-20 07:04 UTC, Aspern requested changes

2023-10-20 07:04 UTC, Aspern commented on isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
> +Ein Bedienkonzept ist eine Sammlung von Designrichtlinien und Standards, die zur Wahrung einer konsistenten visuellen Identität einer Marke oder eines Unternehmens beitragen und konzentriert sich auf
Muss wieder Styleguide heißen (ist ja eine Abgrenzung)

2023-10-20 07:04 UTC, Aspern commented on isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
> +Dieses Bedienkonzept muss von der jeweiligen Behörde ausgearbeitet werden.
Revert: Muss wieder Styleguide heißen

2023-10-20 07:04 UTC, Aspern commented on isyfact-standards-doc/src/docs/antora/modules/isy-bedienkonzept/pages/bedienkonzept.adoc
> +Während das Bedienkonzept in erster Linie für Designer und Entwickler relevant ist, die eine Anwendung entwerfen, ist ein Bedienkonzept eher für Marken- und Kommunikationsexperten relevant, die siche
In dem Absatz muss auch alles auf Styleguide reverted werden

2023-10-20 07:33 UTC, Aspern approved these changes

2023-10-20 07:35 UTC, merged