ISY-305: implement TokenUtil for reading claims from the bearer token
IsyFact/isyfact-standards pull request #111
Opened 2023-10-17 11:32 UTC by tbribram

2023-12-07 14:30 UTC, huebnercl requested changes

2023-12-07 14:30 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/core/Berechtigungsmanager.java
> +     * @deprecated this method is transferred to IsySecurityTokenUtil and will be removed from this interface in a future release
Is it possible to replace the name `IsySecurityTokenUtil` by a link to this new class?

2023-12-07 14:30 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/util/IsySecurityTokenUtil.java
> +    private static String getString(String suffix) {
```suggestion
    private static String getConfigPropertyValueAsString(String suffix) {
```

please use this more expressive method name to recognize and follow more efficiently what's going on.

2023-12-12 09:43 UTC, tbribram commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/util/IsySecurityTokenUtil.java
> +    private static String getString(String suffix) {
Done: https://github.com/IsyFact/isyfact-standards/pull/111/commits/b9c7b551dbd79f2ff590ecc31b8e61c2d4cd380c

2023-12-12 09:43 UTC, tbribram commented on isy-security/src/main/java/de/bund/bva/isyfact/security/core/Berechtigungsmanager.java
> +     * @deprecated this method is transferred to IsySecurityTokenUtil and will be removed from this interface in a future release
Done: https://github.com/IsyFact/isyfact-standards/pull/111/commits/b9c7b551dbd79f2ff590ecc31b8e61c2d4cd380c

2024-01-19 15:08 UTC, huebnercl approved these changes

2024-01-19 15:19 UTC, huebnercl submitted a review, later dismissed

2024-02-26 11:19 UTC, huebnercl approved these changes, later dismissed

2024-03-14 15:37 UTC, huebnercl approved these changes

2024-03-14 15:44 UTC, merged