[Sprint 90] ISY-546: Abraeumen des SecurityContexts im NutzerAuthentifizierungInterceptor
IsyFact/isyfact-standards pull request #160
Opened 2023-11-09 15:12 UTC by sb-sfink

* feat: ISY-546 clear security context in NutzerAuthentifizierungInterceptor
* chore: ISY-546 update changelog in parent and sicherheit submodule

2023-12-20 19:16 UTC, huebnercl approved these changes

2023-12-20 19:18 UTC, huebnercl requested changes
some tests failed

2024-01-04 10:10 UTC, as-materna commented
- [ ] merge after [MR 212](https://github.com/IsyFact/isyfact-standards/pull/212)

2024-01-22 17:38 UTC, huebnercl approved these changes

2024-01-22 18:01 UTC, merged