ISY-737 java language level 17
IsyFact/isyfact-standards pull request #226
Opened 2024-01-10 06:43 UTC by sb-sfink

* build: ISY-737 enforce JDK 17 only
* build: ISY-737 compile for JDK 17 release

    * use default maven.compiler.release property

* chore: ISY-737 remove unused workaround profiles for JDK 11
* docs: ISY-737 compile target: 17
* docs: ISY-737 prepare vor version 4.0.0
* docs: ISY-737 add CHANGELOG.md entry
* feat: ISY-737 migrate to jakarta EE
* chore: ISY-737 remove unused dependencies
* build: ISY-737 set version to 4.0.0-SNAPSHOT

2024-01-31 15:08 UTC, msg-ptavoul commented
Please fix current merge conflicts

2024-01-31 15:11 UTC, msg-ptavoul requested changes
Please fix current merge conflicts

2024-02-22 15:21 UTC, msg-Tomaszewski approved these changes

2024-02-22 15:38 UTC, msg-ptavoul approved these changes

2024-02-22 15:38 UTC, merged