[Sprint 97] ISY-601 Default Actuator Security
IsyFact/isyfact-standards pull request #286
Opened 2024-02-26 13:59 UTC by sb-sfink

* feat: ISY-601 provide security properties
* feat: ISY-601 migrate to AutoConfiguration imports file
* feat: ISY-601 add IsyActuatorSecurityAutoConfiguration

    * disable security for existing tests

* docs: ISY-601 update endpoint security chapter

    * add notice to migration guide
    * update CHANGELOG.md

* test: ISY-601 add ActuatorSecurityTest

2024-02-26 14:02 UTC, frgreiner commented
Depends on 
- [ ] https://github.com/IsyFact/isyfact-standards/pull/287
being merged

2024-02-27 12:14 UTC, mayrklaus approved these changes

2024-02-27 12:20 UTC, mayrklaus requested changes, later dismissed
Quality Gate failed: Test coverage must be improved (required >= 85%, actual < 55%)

2024-03-04 14:02 UTC, mayrklaus commented
Please resolve the above mentioned merge conflicts.
Subsequently, we can check the test coverage problems, that occurred here before

2024-04-18 08:23 UTC, huebnercl requested changes
siehe mehrere Kommentare auch aus abhängigem [ISY-889-Ticket mit MR](https://github.com/IsyFact/isyfact-standards/pull/305)

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/config/ActuatorSecurityConfigurationProperties.java
> +    private String username;
Wäre es nicht sinnvoll, gemäß dem Kommentar, die entsprechende Validierung auf diesem Property in dieser Klasse auf dem Setter einzubauen?
Ansonsten müsste diese an jeder Codestelle implementiert werden, die diesen Setter bzw. diese Klasse verwendet.

siehe auch [den Kommentar](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1555897627)

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                .doesNotHaveBean(UserDetailsService.class)
Soll dies implizit bedeuten, dass die Klasse `UserDetailsService` nur instanziiert wird, wenn ein `username` gesetzt und nicht leer ist, weil falls der `username` gleich NULL würde es keine Instanz von `UserDetailsService` geben?

Diese Logik der Instanziierung sollte klarer kommuniziert, sprich ausführlicher an den entsprechenden Stellen dokumentiert werden. 

siehe auch [den Kommentar](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1555986317)

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                .doesNotHaveBean(PasswordEncoder.class)
Nach welcher Regel existiert kein `PasswordEncoder`?

Bedeutet das, dass `PasswordEncoder` in Abhängigkeit von `UserDetailsService` existiert?

Wäre dies nicht auch eine Dokumentation wert?

siehe auch [den Kommentar](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1555990575)

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/config/ActuatorSecurityTest.java
> +        "isy.logging.anwendung.version=0.0.0-SNAPSHOT",
siehe [offene Conversation](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1556004570)


Es ist m.E. aber irritierend, wenn dann statt mit Pseudo-Daten mit einer realen/validen Versionsnummer hart kodiert gearbeitet wird, aber ohne Hinweis o.ä., dass der angegebene Versionswert auch ein beliebiger Pseudowert sein darf und es nur um die Erfüllung der Annotation `NotEmpty` geht.

2024-04-18 08:23 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
> +Dabei muss beachtet werden, dass über die Endpoints sensible Informationen bereitgestellt werden!
siehe [offene  Conversation](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1556091064)

Soll das bedeuten, dass mit einer Deaktivierung der Standardabsicherung die Endpoints ungesichert erreichbar sind?

Ich kann mir vorstellen, dass dies ggf. in Testumgebungen sinnvoll sein kann, doch für Produktiv-Umgebungen erscheint mir dieses Feature als zu gefährlich, wie es in Zeile 352 als beachtenswert beschrieben ist, auch wenn in dem Ticket eine derartige Anforderung besteht.

Falls dieses Feature erhalten bleiben soll, dann wäre m.E. eine Prüfung sinnvoll, die sicherstellt, dass in einer Produktiv-Umgebung die Absicherung immer aktiv sein muss.

Zum zweite stelle ich mir die Frage, warum für die MonitoringEndpoint-Überwachung keine `ClientRegistration` eines _ConfidentialClients_ der Überwachung verwendet wird und statt dessen hier per `abschaltbarer BasicAuth` die Monitoringendpoint-Überwachung umgesetzt ist?
Wie das im Zusammenspiel mit isy-security und abgesicherten Endpoints durch einfaches Excluden der SecurityAutoConfiguration ablaufen soll, ist mir technisch nicht klar. Gibt es dazu eine detaillierte Dokumentation?

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfiguration.java
> +     * Username can be null (left out of configuration) to secure endpoints without configuring a user to access them.
Dieser Kommentar birgt einen Widerspruch in sich:
Wie kann man einen `Username=NULL` setzen, um auf abgesicherte Endpunkte ohne einen Nutzer konfiguriert zu haben dann zugreifen? Wo und wie soll ohne User aus dem IAM das notwendige Token und Rollen- und Rechte-Set dann herkommen?
Das dürfte prinzipiell doch gar nicht möglich sein, vor allem nicht in einer Produktiv-Umgebung und mit Endpoints, die laut Systemhandbuch sensible Daten austauschen.

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/actuate/health/HealthIntegrationTest.java
> +        "isy.logging.anwendung.version=1.0.0-SNAPSHOT",
siehe [offenen Kommentar](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1555916084)

Ist es sinnvoll die pom-Version von isy-logging hier in einer Testklasse hart codiert aufzunehmen?
Denn sobald diese Version kein Release-Kandidate mehr ist, würde der Test in der Pipeline doch fehlschlagen, oder?

Analog gibt es zu dieser Frage noch eine [offene Conversation](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1556004570)

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                "isy.ueberwachung.security.password="
Mir ist bisher nicht bekannt, dass eine Absicherung per `username / password` mit einem leeren Passwort durch _isy-security_ bzw. von _IAM_ unterstützt werden kann und soll.

Das dürften doch alleine die Methoden-Signaturen von _isy-security_ gar nicht zulassen oder erfolgt diese Absicherung gar nicht über _isy-security_, sondern analog einer interaktiven Authentifizierung über das Portal direkt mit dem IAM?

Nur wie wird dabei zwischen einem _normalen User_ und einem ConfidentialClient unterschieden, wo für letzteren besondere Anforderungen in Bezug auf die Sicherung der UserCredential-Ablage bestehen?

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +    void disabledWithDisabledSecurity() {
Soll das der Testcase sein, bei dem per Exclude die _Absicherung_ abgeschaltet ist?
Nur wo wird dieses Exclude-Property hier verwendet bzw. ausgewertet?

2024-04-18 08:23 UTC, huebnercl commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/config/ActuatorSecurityTest.java
> +        "isy.ueberwachung.security.password=test"
Bitte für `username` und `password` immer unterschiedliche Werte verwenden, um im Test auch sicher zu stellen, dass keine versehentliche Vertauschung der beiden Properties/Parameter gleichen Typs im Code vorhanden ist. 

wurde [gemäß dieser Conversation schon gelöst](https://github.com/IsyFact/isyfact-standards/pull/305#discussion_r1559576711)

2024-04-18 08:23 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
> +----
Wird hier keine Rolle in den Properties mehr benötigt?
Wie bzw. wo wird dann dem User die notwendige Rolle und sein Rechte-Set zugeordnet?

2024-04-19 10:37 UTC, frgreiner commented on isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/config/ActuatorSecurityConfigurationProperties.java
> +    private String username;
Die im Kommentar beschriebene Valierung wird durch die Verarbeitung von Spring Security sichergestellt.

2024-04-19 10:41 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                .doesNotHaveBean(UserDetailsService.class)
siehe Anpassung an der Dokumentation:
https://github.com/IsyFact/isyfact-standards/pull/286/files#diff-4918946b2fb519b6011d57f908ae8cff1b24c6f668ac7064870c51f9bcb8f3a2R336
Das Verhalten ist Dokumentiert.

2024-04-19 10:44 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                .doesNotHaveBean(PasswordEncoder.class)
siehe Autoconfiguration `@ConditionalOn...` Der PasswordEncoder wird nur im UserDetailsService verwendet und muss folglich auch nur dann instanziiert werden, wenn es auch einen UserDetailsService gibt.

2024-04-19 10:46 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/config/ActuatorSecurityTest.java
> +        "isy.logging.anwendung.version=0.0.0-SNAPSHOT",
Ist für das Ziel dieses Tests nicht relevant.

2024-04-19 12:06 UTC, frgreiner commented on isy-ueberwachung/src/main/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfiguration.java
> +     * Username can be null (left out of configuration) to secure endpoints without configuring a user to access them.
Der default Wert ist Null, falls der Nutzername nicht konfiguriert wird.
siehe Nutzungsvorgaben Ueberwachung (Stand vor diesem Ticket) - der Zugriff auf die Actuator Endpunkte ist unabhägig vom IAM System vorgegeben.

2024-04-19 12:20 UTC, frgreiner commented on isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
> +Dabei muss beachtet werden, dass über die Endpoints sensible Informationen bereitgestellt werden!
zur ersten Frage, dieses Ticket wurde so vom Kunden beauftragt und entsprechend der Anforderungen und Lösungsbeschreibung umgesetzt. Falls es Bedenken zur Anforderung gibt, sollten diese mit dem Kunden geklärt werden und nicht die weitere Entwicklung aufhalten, vor allem da diese m.E. unbegründet sind, da die Erreichbarkeit der Actuator Endpunkte von weiteren Faktoren abhängt!

- Standardmäßig sind die Endpunkte abgesichert.
- Die Actuator Endpunkte sind für internes Monitoring gedacht. In Produktion wird für Actuator Endpunkte ein [separater Port konfiguriert](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.actuator.change-http-port-or-address), welcher nur in eine internen Netzwerkzone verfügbar ist.
- Letztendlich ist isy-ueberwachung eine Bibliothek keine Anwendung! Und Anwendungsentwickler haben beliebig viele andere Möglichkeiten diese Absicherung zu deaktivieren, das Verhalten zu überschreiben, ...

Zur zweiten Frage: siehe [Nutzungsvorgaben Überwachung](https://isyfact.github.io/isyfact-standards-doku/current/isy-ueberwachung/nutzungsvorgaben/master.html) - Die Implementierung entspricht so der dokumentierten Vorgabe!

2024-04-19 12:21 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/actuate/health/HealthIntegrationTest.java
> +        "isy.logging.anwendung.version=1.0.0-SNAPSHOT",
bereits beantwortet

2024-04-19 12:23 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +                "isy.ueberwachung.security.password="
Die Actuator Endpunkte sind für interes Monitoring (z.B. mit einem Grafana Dashboard) gedacht und die Absicherung erfolgt ohne IAM.

2024-04-19 12:26 UTC, frgreiner commented on isyfact-standards-doc/src/docs/antora/modules/isy-ueberwachung/pages/nutzungsvorgaben/inhalt.adoc
> +----
Die Zuordnung der Rolle erfolgt in [IsyActuatorSecurityAutoConfiguration](https://github.com/IsyFact/isyfact-standards/pull/286/files#diff-534a8302ae07f30b310661c085e3925ddb880eb322eac667dd4f1397cb8854eaR70). Da die Rolle nur der eindeutigen Zuordnung des speziell für Monitoring angelegten InMemory Users dient, muss diese nicht konfigurierbar sein.

2024-04-19 12:30 UTC, frgreiner commented on isy-ueberwachung/src/test/java/de/bund/bva/isyfact/ueberwachung/autoconfigure/IsyActuatorSecurityAutoConfigurationTest.java
> +    void disabledWithDisabledSecurity() {
Nein, das ist der Testcase, der prüft, dass die AutoConfiguration keine SecurityFilter erstellt, wenn spring-security nicht im Klassenpfad ist.

2024-04-19 14:09 UTC, huebnercl approved these changes
nach Abstimmung mit SB/M am 19.04.2024

2024-04-19 14:12 UTC, merged