docs: IFS-3646 add angular doc to IsyFact doc
IsyFact/isyfact-standards pull request #348
Opened 2024-04-15 13:20 UTC by msg-jstren

2024-04-19 12:15 UTC, stdll requested changes
Ich möchte euch bitten, anstelle der alten Dokumentenstruktur, die sich leider noch überall findet, aber eine technische Schuld ist, eure Inhalte in Seiten zu strukturieren, wie man das auch ansonsten von Online-Dokumentationen kennt.
Hier ist die entsprechende Doku dazu: https://isyfact.github.io/isyfact-standards-doku/current/werkzeuge/seitenvorlage.html

2024-04-30 09:07 UTC, stdll commented on isyfact-standards-doc/src/docs/antora/modules/bausteine/nav.adoc
> +*** xref:isy-angular-widgets-doc:isy-angular-widgets:konzept/konzept.adoc[Konzept]
Wenn ihr meinen Empfehlungen in https://github.com/IsyFact/isy-angular-widgets/pull/198 folgt, muss dieser Verweis auch angepasst werden.

2024-04-30 09:14 UTC, stdll commented on isyfact-standards-doc/src/docs/antora/modules/bausteine/nav.adoc
> +** Angular
Bitte tragt euren Baustein ebenfalls hier ein, einmal in die Grafik und in der Liste: https://github.com/IsyFact/isyfact-standards/edit/master/isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc

2024-05-02 11:59 UTC, stdll submitted a review, later dismissed

2024-05-06 07:23 UTC, Aspern requested changes

2024-05-06 07:23 UTC, Aspern commented on isyfact-standards-doc/src/docs/antora/modules/bausteine/pages/bausteine.adoc
> +bereitgestellt, um User Interfaces zu vereinheitlichen. Der Baustein basiert auf Angular, PrimeNG und PrimeFlex.
```suggestion
|Der Baustein _Angular_ bietet eine Frontend-Bibliothek, deren Komponenten anhand der Vorgaben im Bedienkonzept entwickelt und exemplarisch in der Demo-Anwendung des Bausteins gezeigt werden. 
Dadurch werden wiederverwendbare Widgets bereitgestellt, um User Interfaces zu vereinheitlichen.
Der Baustein basiert auf Angular, PrimeNG und PrimeFlex.
```

2024-05-06 09:22 UTC, Aspern approved these changes

2024-05-06 09:23 UTC, merged