[Sprint 101] IFS-2248 Tokenerneuerung isy batchrahmen 3.x
IsyFact/isyfact-standards pull request #362
Opened 2024-04-25 10:04 UTC by sb-sfink

* feat: IFS-2248 add functionality to check token expiration and availability of AbstractOAuth2TokenAuthenticationToken in SecurityContext, refactor methods
* feat: IFS-2248 add functionality for (re-)authentication to IsyOAuth2Authentifizierungsmanager
* test: IFS-2248 add test cases for token expiration check in IsySecurityTokenUtil
* feat: IFS-2248 add Batchrahmen configuration key for minimum token validity
* feat: IFS-2248 add code for re-authentication to BatchrahmenImpl
* test: IFS-2248 fix token life-time in EmbeddedOidcProviderStub, adjust test classes accordingly in order to avoid failures
* test: IFS-2248 add test cases for authentication in Batchrahmen, adjust tokenLifespan in order to avoid unnecessary re-authentication
* feat: IFS-2248 throw BatchrahmenKonfigurationException when minimum token validity is configured as a negative number, add corresponding test case
* chore: IFS-2248 remove outdated javadoc comment from BatchrahmenImpl
* chore: IFS-2248 update changelog

2024-05-03 08:29 UTC, huebnercl requested changes
mit einem Kommentar bzw. einer Frage zu der in der Lösungsbeschreibung enthaltenen Formulierung:

"...in den **verschiedenen Phasen eines Batch**-Laufes die Überprüfung der Gültigkeit des Access-Tokens..."

2024-05-03 08:29 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/BatchrahmenImpl.java
> +                } else {
Wie kann in Zeile 193 in der Methode `initialisiereBatch()` sichergestellt werden, dass eine evtl. umfangreichere Initialisierung nicht auf ein abgelaufenes Token stößt?

Angenommen bei einem Restart und einem großen schon verarbeiteten Datenvolumen könnte das Ein/Überlesen der schon verarbeiteten Datensätze die Dauer der Tokengültigkeit übertreffen.

Das heißt die grundsätzliche Frage lautet: Wie kann in der Batch-Initialisierungs- und Batch-Beendingungsphase - in Zeile 243 in der Methode `beendeBatch()` - sichergestellt werden, dass die Mindestgültigkeitsdauer des Tokens nicht unterschritten bzw. gänzlich abläuft?

2024-05-17 13:21 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/BatchrahmenImpl.java
> +                } else {
Das betrifft doch allgemein nur den Fall, dass innerhalb einer `BatchAusfuehrungsBean` (`intialisieren`/`verarbeiteSatz`/`batchBeendet`/...), die von der Anwendung implementiert wurde, das Token an andere Systeme weitergegeben wird und es abläuft bevor es dort verifiziert und in dessen SecurityContext aufgenommen wurde.
Solange wir uns nur intern in der Anwendung befinden die den Batch ausführt bzw. diese Requests abschickt die entweder das Token nicht brauchen (bspw. Datenbankabfrage) bzw. ein eigenes Token benutzen (Verwendung eines Clients der einen eigenen technischen Nutzer hat) wird vor dem jeweiligen Schritt ein gültiges Token ermittelt und die Rollen daraus in den SecurityContext geschrieben. Anschließend ist die Gültigkeit des Tokens irrelevant.

Da die Anwendung keine Kontrolle über die exakte Gültigkeitsdauer des Tokens hat, ist die beste Möglichkeit diese zu maximieren das Token direkt vor der Anfrage eines anderen Systems zu erneuern. Und die Verantwortung dafür kann nur in der Anwendung selber und nicht in `isy-batchrahmen` liegen.

2024-06-03 20:39 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/BatchrahmenImpl.java
> +                } else {
Aber das ist doch genau der Punkt den ich angemerkt habe:
Die `BatchRahmenImpl` ruft nach einer gültigen Authentifizierung die interne Methode `initialisiereBatch` auf. Damit liegt für den Start der Initialisierungsphase ein gültiges Token vor. In der Initialisierungsmethode selbst werden die Datenbanktabellen des Batch ausgelesen, um bei evtl. vorherigen Batchläufen den schon verarbeiteten Status zu ermitteln. 

Angenommen die zuvor verarbeiteten Daten wurden über Serviceaufrufe einer Geschäftsanwendung zusammengetragen und aufgrund des vorherigen Batchlaufes müssen nun von dieser Geschäftsanwendung erst die Daten für den aktuellen Batchlauf mittels mehrerer Serviceaufrufe erneut gemäß Verarbeitungsstatus ermittelt werden. 

Wie kann sichergestellt werden, dass während dieser Datenermittlung und den mehrfachen Serviceaufrufen das Token nicht abläuft bzw. rechtzeitig erneuert wird?

Das analoge Szenario wenn nach der Verarbeitungsschleife bzw. in der internen Methode `beendeBatch` die Ergebnisse der Batchverarbeitung eine aufwändigere Nachverarbeitung wiederum mit evtl. mehreren Serviceaufrufen anderer Geschäftsanwendungen benötigt.

2024-06-03 22:16 UTC, huebnercl requested changes
siehe erneute Anmerkungen zu dem Thema

2024-06-05 22:29 UTC, huebnercl approved these changes, later dismissed

2024-06-05 22:29 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/core/rahmen/impl/BatchrahmenImpl.java
> +                } else {
Die Tokenprüfung mit evtl. Erneuerung wurde wie besprochen eingebaut.

2024-07-08 18:16 UTC, msg-Tomaszewski approved these changes

2024-07-08 18:16 UTC, merged