IFS-1854: Umsetzung Berechtigungsmanager
IsyFact/isyfact-standards pull request #40
Opened 2023-06-30 07:22 UTC by frgreiner

* feat: IFS-1854 add Berechtigungsmanager implementation
  * add unit test
  * add documentation
* chore: IFS-1854 update changelog
* chore: IFS-1854 add interface and javadoc
* docs: IFS-1854 change image id syntax

2023-07-03 12:23 UTC, frgreiner commented
- [ ] depends on https://github.com/IsyFact/isyfact-standards/pull/39

2023-07-14 15:27 UTC, huebnercl requested changes
only a few comments and questions...

2023-07-14 15:27 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/Berechtigungsmanager.java
> +    Object getTokenAttribute(String key);
This public method was not requested and the implementation of the `DefaultBerechtigungsmanager` for this method opens the following questions:
- Does it make sense to shift this method in the context of an `Authentication`-Implementation like an existing or new implementations of the interface `AbstractOAuth2TokenAuthenticationToken`?
- if the method `getTokenAttribute` is only used in the `DefaultBerechtigungsmanager` then its scope should be changed to **private** and removed here from interface, right?
- If this method is introduced for future access on general token attributes, is this interface of the `BerechtigungsManger` the right place, because an implementation of this interface should only care about _roles_ and _rights_ and not other attributes, which are possibly part of a token?

2023-07-14 15:27 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/DefaultBerechtigungsmanager.java
> +    }
see comment and questions in the interface `Berechtigungsmanager`

2023-07-14 15:27 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/BerechtigungsmanagerTest.java
> +
what about negativ testcases for:
- missing roles, because of malconfiguration
- missing rights because of malconfiguration
- missing token because of unauthenticated user
- ...

2023-07-14 15:27 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
> +- `IFS-2403`: Abschnitt zum OpenId Connect Provider Mock aus isy-security-test hinzugefügt
are these tickets parts of the dependency-chain of IFS-1960-1854-... ?

2023-07-14 15:27 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`Object getTokenAttribute(String key)`:: Fragt einen Wert im Access Token des Security Contexts ab.
see also comment in implementation of `Berechtigungsmanager`, if this method is here in the right place?
a suggestion would be to shift it in a class managing token aspects like `IsyOAuth2PasswordAuthenticationToken`

2023-08-07 08:26 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/Berechtigungsmanager.java
> +    Object getTokenAttribute(String key);
In Abstimmung mit @huebnercl und @kollmana soll die Methode, wie umgesetzt, beibehalten bleiben.

2023-08-09 09:09 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/BerechtigungsmanagerTest.java
> +
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:11 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
> +- `IFS-2403`: Abschnitt zum OpenId Connect Provider Mock aus isy-security-test hinzugefügt
Materna prüft nach dem Mergen, ob die Changelogs korrekt sind.

2023-08-09 10:22 UTC, huebnercl submitted a review, later dismissed

2023-08-09 14:22 UTC, dauna-msg submitted a review, later dismissed

2023-08-09 14:30 UTC, dauna-msg approved these changes, later dismissed

2023-08-10 14:54 UTC, closed without merging

2023-08-10 14:55 UTC, dauna-msg commented
Geschlossen.