IFS-2400 Security- and Authentifizierungsmanager interface
IsyFact/isyfact-standards pull request #41
Opened 2023-06-30 07:25 UTC by frgreiner

* test: IFS-2400 cover both flows with assertions
* feat: IFS-2400 add header for bhknz
* feat: IFS-2400 add property for standard OU
* feat: IFS-2400 enable caching for client credentials authentication by client registration
* feat: IFS-2400 split autoconfiguration for conditional bean creation
* feat: IFS-2400 bundle common functionality of Isy..AuthenticationProviders in abstract superclass
* feat: IFS-2400 rename AutoConfiguration
* test: IFS-2400 check authorizedClient caching is used
* test: IFS-2400 test autoconfiguration conditions
* chore: IFS-2400 update CHANGELOG.md
* style: IFS-2400 remove checkstyle warnings

    * add javadoc
    * add package-info

* docs: IFS-2400 describe usage of the Security and Authentifizierungsmanager interface
* feat: IFS-2400 move IsyOAuth2Authentifizierungsmanager to core package with @NonNullApi
* feat: IFS-2400 interface method signature changed to sort the parameters in logical order

    * spring -> isyfact specific -> optional

* feat: IFS-2400 rename default implementations with IsyOAuth2* prefix

    * indicate class is isyfact specific and OAuth2 related

* chore: IFS-2400 fix javadoc typo
* test: IFS-2400 move AutoConfiguration specific Testcase into IsySecurityAutoConfigurationTest
* feat: IFS-2400 add support for @AutoConfiguration, improve javadoc, fix typos
* refactor: IFS-2400 move oauth client related classes to the oauth.client package
* refactor: IFS-2400 shorten names of provider classes for better readability, add minor improvements
* refactor: IFS-2400 move Security and Berechtigungsmanager interfaces to core package
* feat: IFS-2400 refactor oauth classes for better testability
* test: IFS-2400 add more tests, refactor existing tests
* fest: IFS-2400 fix NPE in RolePrivilegesMapper
* build: IFS-2400 cleanup maven dependencies (see IFS-2481)

2023-07-03 12:24 UTC, frgreiner commented
- [ ] depends on https://github.com/IsyFact/isyfact-standards/pull/40

2023-07-20 18:55 UTC, huebnercl requested changes
very good work, more testcases and details than expected...
several comments and questions especially depending on the current state of the open decisions of our meeting from 06.07.2023

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +     *     <li>Resource Owner Password Credentials (grant type: password)</li>
```suggestion
     *     <li>Client Credentials Flow (grant type: client_credentials)</li>
     *     <li>Resource Owner Password Credentials Flow (grant type: password)</li>
```

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +    void authentifiziere(String registrationId) throws AuthenticationException;
```suggestion
     * @param clientRegistrationId
     *         ID of the OAuth 2.0 Client to authorize
     * @throws AuthenticationException
     *         if authentication fails
     */
    void authentifiziere(String clientRegistrationId) throws AuthenticationException;
```

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +     * Attempts to authorize the client for the given {@code registrationId} via its configured OAuth 2.0 Flow.
```suggestion
     * Attempts to authorize the client for the given {@code clientRegistrationId} via its configured OAuth 2.0 Flow.
```

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +    void authentifiziereClient(String clientId, String clientSecret, String issuerLocation) throws AuthenticationException;
as decided and decribed in the meeting protocol from 06.07.2023:
- additional parameter `clientRegistrationId` for the clientregistration configuration of the intermediary - here SGW
- the parameter `issuerLocation` will be removed, because it can be retrieved over the `clientRegistrationId`
- the parameters `clientId` and `clientSecret` are client credentials from an external client not part of the local configuration for example of the SGW
- additional parameter `bhknz` to support optional 2FA
- this method is intended to be used where the invoker - here SGW - knows before invokation that a client credential flow has to be used for authentication

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +            AuthenticationException;
as decided and decribed in the meeting protocol from 06.07.2023:
- rename the parameter `registrationId` to `clientRegistrationId` to avoid confusion between an applicationRegistrationId and a clientRegistrationId
- the `username` and `password` parameters are authentication data from an external client, which is still not migrated to a client and are not part of a local configuration especially not part of the intermediary configuration
- this method is intended to be used where the invoker - here SGW - knows before invokation that a _resource owner password credential_ flow has to be used for authentication
- with the _resource owner password credential_ flow an implicite authentication of the intermediary has to be processed before the client authentication will take place

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +    public void authentifiziereClient(String clientId, String clientSecret, String issuerLocation) throws AuthenticationException {
please see comments to this method in the interface `AuthentifizierungsManager`

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +    public void authentifiziereSystem(String registrationId, String username, String password, @Nullable String bhknz)
please see comments to this method in the interface `AuthentifizierungsManager`

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +     * The registrationId (String key of the Map) must match the registrationId in the corresponding Spring OAuth 2.0 client properties.
exactly speaking `registrationId` means `clientRegistrationId` of the spring configuration properties with prefix `spring.security` matching with the additional custom properties prefix `isy.security` and must be defined in the regular application configuration as property
`<application-type-prefix>.<applicationRegistrationId>.clientRegistrationID`

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +    private String bhknzHeaderName = "x-client-cert-bhknz";
if this is a configurable header name for 2FA, why is it defined in hardcoded manner than part of a property configuration?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +    }
if `bhknzHeaderName` and `defaultCertificateOu` are configurable, why are they  never read from configuration?
Is it correct to define them as `spring.security`properties or should they be part of the `isy.security`- propertyset?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +    private final ProviderManager providerManager;
which prerequisits are necessary to support all authentication methods of this class?
Are they requirements of the configuration and if yes, which properties have to be defined?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +    public void authentifiziere(String registrationId) throws AuthenticationException {
please see comments to this method in the interface `AuthentifizierungsManager`

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +        if (AuthorizationGrantType.CLIENT_CREDENTIALS.equals(grantType)) {
is it possible to ensure a correct initialization of the providerManager to support the configured credential flow by the property grantType before this if-clause will be processed and may end in an AuthenticationException as mentioned in the class description?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +        authenticateAndChangeAuthenticatedPrincipal(token);
is it possible to ensure a correct initialization of the providerManager to support the configured credential flow by the property grantType before this method will be processed and may end in an AuthenticationException as mentioned in the class description?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/IsyOAuth2AuthenticationProvider.java
> +        Jwt jwt = jwtDecoderFactory.createDecoder(clientRegistration).decode(accessToken.getTokenValue());
Isn't it necessary to check if the `accessToken` of the given `authorizedClient` return `isAuthenticated() = true` before going on to create and return a JWT?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProvider.java
> +public class ManualClientCredentialsAuthenticationProvider extends IsyOAuth2AuthenticationProvider {
What is the background for this second kind of client-credential provider implementation? 
It is not in use by the `IsyOAuth2Authentifizierungsmanager` while the `ManualClientCredentialsAuthenticationToken` is used.
Perhaps it would be the better choice of a client-credential provider for the method `authentifziereClient()` than the  `ClientCredentialAuthenticationProvider`, because this method will always gets the authentication data `clientId/clientSecret` as parameter from incoming request of an external application.

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProvider.java
> +                .clientSecret(token.getClientSecret())
if this provider is planed to be used by the method `authentifziereClient(clientRegistrationId, clientId, clientSecret, bhnkz)` then it has to take care, that the `ClientRegistration` will be created over the `clientRegistrationId` of the intermediary (SGW), which will define the `issuerLocation`. Because the `clientId` and `clientSecret` are not the values of the intermediary-configuration, but the authentication data of the request from the external application.

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProvider.java
> +    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
missing the treatment for the optional parameter `bhknz` for the client credential flow as decided in the meeting from 06.07.2023

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProvider.java
> +                .build();
the name `responseClient` of type `OAuth2AccessTokenResponseClient<OAuth2PasswordGrantRequest>` is quite confusing on buildup a request to `authorize` a client per _ResourceOwnerPasswordCredential_ flow`.

Why using/naming _response_ types and components, when creating an authorize _request_?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProvider.java
> +        return passwordTokenResponseClient;
the optional parameter `bhknz` is transferred in the HTTP-Header of the request from the external Application. It is extracted in the SGW by interpreting the Client-Certificate including the `OrganisationUnit` of the external Application, right?
So, is this correct to get the `OrganisationUnit` from the configured ClientRegistrationProperties of the SGW instead of using it from the extracted HTTP-Header of the external application request?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationToken.java
> +public class PasswordAuthenticationToken extends AbstractAuthenticationToken {
should this type of token be prepared to transfer the `organisation-unit` from the HTTP-Header of the request from the external application too?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/autoconfigure/IsySecurityAutoConfigurationTest.java
> +    }
what about tests with the additional OAuth2Property `isy.security.oauth2.client.registration.test.bhknz` ?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerTest.java
> +                .authorizationGrantType(AuthorizationGrantType.PASSWORD).build();
is a test for a ropcClient without the additional properties username, password and bhknz valid?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerTest.java
> +
missing a test like `testAuthSystemWithRegistrationId` but with getting the values for `username`, `password` and `bhknz` from additional configuration properties with prefix `isy.security` instead of testing against the token-class default values.

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsAuthenticationProviderTest.java
> +        verify(0, postRequestedFor(urlEqualTo(ISSUER_PATH + "/protocol/openid-connect/token")));
to reuse still valid or authorized data seems quite good.
But the questions are:
- On which rules the logic will decide if a client is still authorized or if a new token has to fetch?
- Is there a test, if the token of the authorized client is still valid and will not expire in a near time? 
- What is the minimum timeperiod till expiration time a token will be classified as valid?
- Are there other rules independent from the token, like ´max_keep-in-cache-duration` for an authorized client instance, which decide to reuse a client? 
- Does these rules of reusage decrease the security-level compared against a full authentication of a client each time?

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProviderTest.java
> +                jwtAuth.getTokenAttributes().get(StandardClaimNames.PREFERRED_USERNAME));
is this assert statemtent correct?
- the previous `authenticate` method in this _client-credential_-flow uses the `clientid/clientSecret` authentication-data as parameters, but this `assert` checks for a different `clientId`-value and the `claimName=PREFERRED_USERNAME` seems not correct too

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProviderTest.java
> +    }
within these testcases the validation checks for the same values as in the previous testcases `shouldGetAuthTokenForUserWith(out)Bhknz` where the values are given per parameter. 

So it is not clear if the logic of the previous testcases realy takes the values from the parameters or from the configuration of the clientregistration.

Please use different clientregistrations or different username and password values to ensure if the values are used from given parameters or from configuration.

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProviderTest.java
> +    }
is this a valid testcase, because the parameter `bhknz` is an optional one even for the _Resource-Owner-Password-Credential_ Flow?

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/authentifizierungsmanager.svg
what's the current state about the decitions of our meeting from 06.07.2023:
- Is it planed to reduce confusions about the parameter naming of `registrationId` for example renaming to `clientRegistrationId` or to refactor to `applicationId`? 
- is it planed to harmonize the method signatures to:
  -  `authentifiziereClient(String applicationId, String clientId, String clientSecret, @Nullable String bhknz)`
  -  `authentifiziereSystem(String applicationId, String username, String password, @Nullable String bhknz)`

Because here in msg we started to modify the documentation on base of these decisions.

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/core/Berechtigungsmanager.java
> +    Object getTokenAttribute(String key);
please see the comment in IFS-1854 about this new method.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/berechtigungsmanager.svg
please see the comment in IFS-1854 about this new method `getTokenAttribute()`.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
missing the changelog for IFS-2400.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Zur manuellen Authentifizierung von Clients stehen folgende Methoden zur Verfügung:
```suggestion
Zur programmatischen Authentifizierung von Clients stehen folgende Methoden zur Verfügung:
```
the word `manuell` suggerates an interaction by the user, but the methods of `AuthentifizierungsManager` are without any interactions during runtime.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`void authentifiziereSystem(String registrationId, String username, String password, @Nullable String bhknz)`:: Authentifiziert einen Client anhand `registrationId`, `username`, `password`  und (opti
What about the current state of the decisions of our meeting from 06.07.2023?

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`Object getTokenAttribute(String key)`:: Fragt einen Wert im Access Token des Security Contexts ab.
please see the comment in IFS-1854 about this new method getTokenAttribute().

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +|===
a confidential client like SGW, Batch, Task, ... only knows their `applicationId`, which they get during startphase. To set the correct `clientRegistrationId` the application configuration needs an indirection configuration property, to navigate from the `applicationId` to the correct _client-registration-properties_.
The configuration for this indirection will be done by defining a new property: `<prefix-application>.<applicationId>.clientregistrationID=`

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +=== Manuelle Authentifizierung eines Clients mit dem Authentifizierungsmanager
```suggestion
=== Programmatische Authentifizierung eines Clients mit dem Authentifizierungsmanager
```
please see comment in line 96-110 too.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Die manuelle Authentifizierung eines Client erfolgt über den Authentifizierungsmanager, der entsprechende Methoden zur Verwendung mit und ohne zuvor konfigurierte `ClientRegistrations` bereitstellt.
```suggestion
Die programmatische Authentifizierung eines Client erfolgt über den Authentifizierungsmanager, der entsprechende Methoden zur Verwendung mit und ohne zuvor konfigurierte `ClientRegistrations` bereitstellt.
```
please see the comment in line 96-110 too.

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Die im <<listing-client-registrations>> konfigurierten Isyfact spezifischen ClientRegistration properties werden nicht benötigt, da die Zugangsdaten dynamisch zur Laufzeit als Methodenparameter überg
What about the current state of the decisions of our meeting from 06.07.2023?

will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-07-20 18:55 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +----
missing the indirection from `applicationId` to `clientregistrationID` as mentioned in comment of line 96-110

2023-07-25 14:07 UTC, frgreiner commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +    void authentifiziere(String registrationId) throws AuthenticationException;
Der Parameter bezieht sich auf die von Spring ebenfalls so genannte `registrationId`, see: https://docs.spring.io/spring-security/reference/servlet/oauth2/client/core.html

2023-08-01 19:32 UTC, huebnercl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/Authentifizierungsmanager.java
> +    void authentifiziere(String registrationId) throws AuthenticationException;
will be solved or be part in the successive issue https://tracker.seitenbau.net/browse/ISY-147

2023-08-07 11:51 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +    private String bhknzHeaderName = "x-client-cert-bhknz";
Evt. default-Wert, falls kein Wert konfiguriert wird?

2023-08-09 09:27 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +     * The registrationId (String key of the Map) must match the registrationId in the corresponding Spring OAuth 2.0 client properties.
Wird im Rahmen der Anhebung der QAs auf IF 3 erneut geprüft, ob hier eine weitere Unterstützung des Bausteins erforderlich ist.

2023-08-09 09:29 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/config/IsyOAuth2ClientConfigurationProperties.java
> +    private String bhknzHeaderName = "x-client-cert-bhknz";
Default-Wert, kann geschlossen werden.

2023-08-09 09:32 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +    private final ProviderManager providerManager;
Wird in einem Nachfolgerticket isy-147 angepasst.

2023-08-09 09:34 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +        if (AuthorizationGrantType.CLIENT_CREDENTIALS.equals(grantType)) {
Wird in isy-147 umgesetzt.

2023-08-09 09:34 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/IsyOAuth2Authentifizierungsmanager.java
> +        authenticateAndChangeAuthenticatedPrincipal(token);
Wird in isy-147 umgesetzt.

2023-08-09 09:36 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/IsyOAuth2AuthenticationProvider.java
> +        Jwt jwt = jwtDecoderFactory.createDecoder(clientRegistration).decode(accessToken.getTokenValue());
Access-Token ist immer authentifiziert, wenn es vom IAM zurückkommt.

2023-08-09 09:39 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProvider.java
> +                .clientSecret(token.getClientSecret())
Token ist hier nicht der Access-Token, sondern das Transportobjekt an IAM.

2023-08-09 09:41 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProvider.java
> +                .build();
Bleibt bestehen analog zu den Spring Namenskonventionen.

2023-08-09 09:44 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProvider.java
> +        return passwordTokenResponseClient;
Diese Methode wird nicht für die Authentifizierung von externen Systemen verwendet, daher ist die Implementierung korrekt.

2023-08-09 09:45 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationToken.java
> +public class PasswordAuthenticationToken extends AbstractAuthenticationToken {
Diese Methode wird nur für die interne Authentifizierung verwendet, daher ist die Implementierung korrekt.

2023-08-09 09:47 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/autoconfigure/IsySecurityAutoConfigurationTest.java
> +    }
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:47 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerTest.java
> +                .authorizationGrantType(AuthorizationGrantType.PASSWORD).build();
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:48 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/AuthentifizierungsmanagerTest.java
> +
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:48 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ClientCredentialsAuthenticationProviderTest.java
> +        verify(0, postRequestedFor(urlEqualTo(ISSUER_PATH + "/protocol/openid-connect/token")));
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:49 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/ManualClientCredentialsAuthenticationProviderTest.java
> +                jwtAuth.getTokenAttributes().get(StandardClaimNames.PREFERRED_USERNAME));
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:49 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProviderTest.java
> +    }
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:49 UTC, dauna-msg commented on isy-security/src/test/java/de/bund/bva/isyfact/security/oauth2/client/authentication/PasswordAuthenticationProviderTest.java
> +    }
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 09:50 UTC, dauna-msg commented on isy-security/src/main/java/de/bund/bva/isyfact/security/core/Berechtigungsmanager.java
> +    Object getTokenAttribute(String key);
Bleibt bestehen.

2023-08-09 09:51 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/images/nutzungsvorgaben/berechtigungsmanager.svg
Bleibt bestehen.

2023-08-09 09:51 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
Changelogs werden von Materna zum Release hin noch einmal überprüft.

2023-08-09 09:54 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Zur manuellen Authentifizierung von Clients stehen folgende Methoden zur Verfügung:
Wird in isy-147 nachgezogen, sodass die Unterschiede zwischen den Authentifizierungsarten klar dargestellt werden.

2023-08-09 09:54 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`Object getTokenAttribute(String key)`:: Fragt einen Wert im Access Token des Security Contexts ab.
Bleibt bestehen.

2023-08-09 09:55 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +----
Wird im Rahmen der Anhebung der QAs auf IF 3 erneut geprüft, ob hier eine weitere Unterstützung des Bausteins erforderlich ist.

2023-08-09 09:56 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +|===
Wird im Rahmen der Anhebung der QAs auf IF 3 erneut geprüft, ob hier eine weitere Unterstützung des Bausteins erforderlich ist.

2023-08-09 10:28 UTC, huebnercl submitted a review, later dismissed

2023-08-10 10:41 UTC, dauna-msg approved these changes, later dismissed

2023-08-10 10:43 UTC, dauna-msg approved these changes, later dismissed

2023-08-10 14:45 UTC, dauna-msg submitted a review, later dismissed

2023-08-10 14:46 UTC, Aspern approved these changes

2023-08-10 14:48 UTC, dauna-msg submitted a review, later dismissed

2023-08-10 14:49 UTC, Aspern approved these changes, later dismissed

2023-08-10 15:29 UTC, dauna-msg commented
Geschlossen, da aufgrund eines Bugs nicht mergebar.

Neuer Merge Request: https://github.com/IsyFact/isyfact-standards/pull/63

2023-08-10 15:29 UTC, closed without merging