IFS-2416 Umstellung task auf security
IsyFact/isyfact-standards pull request #42
Opened 2023-06-30 07:29 UTC by frgreiner

* feat: IFS-2416 add isy-security to isyfact-standards-bom Version management
* feat: IFS-2416 add isy-security dependency
* feat: IFS-2416 rename AuthenticatorFactory
* feat: IFS-2416: replace implementation based on isy-security
* test: IFS-2416 fix test execution with junit5
* feat: IFS-2416 remove unused isy-aufrufkontext dependency
* chore: IFS-2416 update CHANGELOG.md
* docs: IFS-2416 update authentication properties description
* feat: IFS-2416 check only whitespaces in registrationId
* test: IFS-2416 add empty rollenrechte.xml

    * WORKAROUND: required due to transitive dependency to isy-security via isy-task

* refactor: IFS-2416: moves rollenrechte.xml to default path
* docs: IFS-2416: update reference to isy-security
* refactor: IFS-2416: move classes to security package
* test: IFS-2416: NullPointerException on invalid TaskID
* feat: IFS-2416: prevent NullPointerException on invalid TaskID

2023-07-03 12:24 UTC, frgreiner commented
- [ ] depends on https://github.com/IsyFact/isyfact-standards/pull/41

2023-07-26 13:59 UTC, huebnercl requested changes
some small comments and questions

2023-07-26 13:59 UTC, huebnercl commented on CHANGELOG.md
> +  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur Authentifizierung
```suggestion
  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über `isy-security`-ClientRegistrations und für IsyTaskConfigurationProperties muss eine `clientRegistrationID` als Indirektion zu den `isy-security`-Properties konfiguriert werden.
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/CHANGELOG.md
> +    * BREAKING CHANGE: Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur
```suggestion
      * BREAKING CHANGE: Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über `isy-security`-ClientRegistrations und für IsyTaskConfigurationProperties muss eine `clientRegistrationID` als Indirektion zu den `isy-security`-Properties konfiguriert werden.
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
```suggestion
        /** ClientRegistration-ID for authentication. **/
        private String clientRegistrationId;
```
Please rename the `registrationId` in all cases to `clientRegistrationId` to distingue this identifier from the `applicationId` or here in this context `taskId`.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public String getRegistrationId() { return registrationId; }
```suggestion
        public String getClientRegistrationId() { return clientRegistrationId; }
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
```suggestion
        public void setClientRegistrationId(String clientRegistrationId) { this.clientRegistrationId = clientRegistrationId; }
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
```suggestion
        /** ClientRegistration-ID for authentication. **/
        private String clientRegistrationId;
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
```suggestion
        public String getClientRegistrationId() { return clientRegistrationId; }

        public void setClientRegistrationId(String clientRegistrationId) { this.clientRegistrationId = clientRegistrationId; }
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +    private final String registrationId;
```suggestion
    private final String clientRegistrationId;
```
please emphasize the different types of identifiers - `task applicationRegistrationId` and `clientRegistrationId` - from configuration in the code too.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        this.registrationId = registrationId;
```suggestion
     * @param clientRegistrationId Registration-ID of the client
     */
    public IsySecurityAuthenticator(
            Authentifizierungsmanager authentifizierungsmanager,
            String clientRegistrationId
    ) {
        this.authentifizierungsmanager = authentifizierungsmanager;
        this.clientRegistrationId = clientRegistrationId;
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        authentifizierungsmanager.authentifiziere(registrationId);
```suggestion
        authentifizierungsmanager.authentifiziere(clientRegistrationId);
```

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +            }
```suggestion
            String clientRegistrationId = configurationProperties.getTasks().get(taskId).getClientRegistrationId();
            if (StringUtils.hasText(clientRegistrationId)) {
                return new IsySecurityAuthenticator(
                        authentifizierungsmanager,
                        clientRegistrationId
                );
            }
```

as mentioned in previous reviews to the topic `isy-security` and decided in the meeting from 06.07.2023 to reduce and eliminate confusions, it is important to distingue between _registrationIds_ of type `applicationRegistrationId` and `clientRegistrationId`.
the property key of the indirection from _application configuration_ to _spring.security/isy.security configuration_ is named `...clientregistrationId=<value>`
so please keep it consistent over all, the usage of isy-security as isy-security intern.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +                    defaultRegistrationId
```suggestion
        String defaultClientRegistrationId = configurationProperties.getDefault().getClientRegistrationId();
        if (StringUtils.hasText(defaultClientRegistrationId)) {
            String nachricht = MessageSourceHolder
                    .getMessage(HinweisSchluessel.VERWENDE_STANDARD_KONFIGURATION, "clientRegistrationId");
            LOG.info(LogKategorie.SICHERHEIT, HinweisSchluessel.VERWENDE_STANDARD_KONFIGURATION, nachricht);
            return new IsySecurityAuthenticator(
                    authentifizierungsmanager,
                    defaultClientRegistrationId
```

as mentioned in previous reviews to the topic isy-security and decided in the meeting from 06.07.2023 to reduce and eliminate confusions, it is important to distingue between registrationIds of type `applicationRegistrationId` and `clientRegistrationId`.
the property key of the indirection from _application configuration_ to _spring.security/isy.security configuration_ is named `...clientregistrationId=<value>`
so please keep it consistent over all, the usage of isy-security as isy-security intern.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthenticationTasks.java
>      }
the annotation `@Secured` checks if a previous authenticated user has the rights, set with the annotation itself. 

But here in the Test-Framework all TestTasks are implicite authenticated by the annotation `@Scheduled`, so the `@Secured` annotation will never be tested without a previous authentication.

Missing a testcase to check the behaviour of the annotation `@Secured` without a previous authentication or with missing authentication data like the access-token or the user-roles and -rights.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthentication.java
>      }
line 78-98
the annotation `@Secured` checks if a previous authenticated user has the rights, set with the annotation itself. 

But here in the Test-Framework all TestTasks are implicite authenticated by the annotation `@Scheduled`, so the `@Secured` annotation will never be tested without a previous authentication.

Missing a testcase to check the behaviour of the annotation `@Secured` without a previous authentication or with missing authentication data like the access-token or the user-roles and -rights.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/monitoring/IsyTaskAspect.java
**a comment outside the requirements of the ticket IFS-2416 (but worth to know for isy-task component):**
line 91:
...
`Authenticator authenticator = authenticatorFactory.getAuthenticator(taskId);`

the logic to get an authenticator per `taskId` includes on missing configured `taskId` to search and use the default task-configuration settings.

in line 100:
...
`taskConfig = isyTaskConfigurationProperties.getTasks().get(taskId);`

here this implicit logic to use the default task-configuration is missing. 

Isn't that an unexpected behaviour if a default task-configuration is administrated, but will not be used?

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactoryTest.java
> +    }
what about the fallback to use the default task-configuration in case of missing `taskId`-configuration?

But it's very good to test the case if no configurations can found at all for the task...

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/resources/application.properties
> +isy.task.tasks.testTaskAuthenticationTasks-scheduledTaskSecured.registration-id=ropc-testclient
doesn't it make sense to define for the `resource-owner-password-credential` flow a second clientregistration with insufficient rights too, to test the authentication with negativ results?

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/resources/application.properties
> +isy.task.tasks.testTaskAuthenticationTasks-scheduledTaskSecuredInsufficientRights.registration-id=cc-testclient
doesn't it make sense to define for the `client-credential` flow a second clientregistration with sufficient rights too, to test the authentication with positiv results?

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/resources/application-security-test.properties
> +spring.security.oauth2.client.registration.cc-testclient.provider=testrealm
please see comments in `application.properties` concerning the definitions of client-registrations.

2023-07-26 13:59 UTC, huebnercl commented on isy-task/src/test/resources/resources/sicherheit/rollenrechte.xml
does it make sense to rename the part `sicherheit` in this path to `security` too, to reach a consistent naming for the switch from `isy-sicherheit` to `isy-security`?

2023-07-26 13:59 UTC, huebnercl commented on isy-ueberwachung/src/test/resources/resources/sicherheit/rollenrechte.xml
does it make sense to rename the part `sicherheit` in this path to `security` too, to reach a consistent naming for the switch from `isy-sicherheit` to `isy-security`?

2023-07-26 13:59 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
line 193:
...
`taskKonfiguration.setAuthenticator(new NoOpAuthenticator());`
...

Isn't it more interesting to describe a programmatic configuration example with a clientregistration authentication?

2023-07-26 13:59 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
with the switch from `isy-sicherheit` to `isy-security` and the usage of an access-token for an authenticated user, which have an expiration time and the still open feature of a cyclic check for a still valid accesstoken during the task-processing-loop, isn't it necessary to describe in this document what the developer/devop/user could do in case the access-token expire during task processing or before all processingsteps are finished ?

2023-08-01 19:47 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:48 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public String getRegistrationId() { return registrationId; }
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:48 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:48 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:49 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:49 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +    private final String registrationId;
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:49 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        this.registrationId = registrationId;
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:49 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        authentifizierungsmanager.authentifiziere(registrationId);
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:50 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +            }
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-01 19:50 UTC, huebnercl commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +                    defaultRegistrationId
base on the successive issue https://tracker.seitenbau.net/browse/ISY-147 of IFS-2400

2023-08-07 11:28 UTC, dauna-msg commented on CHANGELOG.md
> +  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur Authentifizierung
Wird mit isy-147 umgesetzt.

2023-08-07 11:29 UTC, dauna-msg commented on isy-task/CHANGELOG.md
> +    * BREAKING CHANGE: Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur
Wird mit isy-147 umgesetzt.

2023-08-07 11:29 UTC, dauna-msg commented on isy-task/src/test/resources/application-security-test.properties
> +spring.security.oauth2.client.registration.cc-testclient.provider=testrealm
Wird mit isy-147 umgesetzt.

2023-08-07 11:30 UTC, dauna-msg commented on isy-task/src/test/resources/resources/sicherheit/rollenrechte.xml
Pfad wird beibehalten.

2023-08-09 09:57 UTC, dauna-msg commented on isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthenticationTasks.java
>      }
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 10:00 UTC, dauna-msg commented on isy-task/src/main/java/de/bund/bva/isyfact/task/monitoring/IsyTaskAspect.java
Schaut sich der SWEDL an.

2023-08-09 10:00 UTC, dauna-msg commented on isy-task/src/test/resources/application.properties
> +isy.task.tasks.testTaskAuthenticationTasks-scheduledTaskSecured.registration-id=ropc-testclient
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 10:01 UTC, dauna-msg commented on isy-task/src/test/resources/application.properties
> +isy.task.tasks.testTaskAuthenticationTasks-scheduledTaskSecuredInsufficientRights.registration-id=cc-testclient
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 10:03 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Nimmt sich der SWEDL mit.

2023-08-09 10:05 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Wird in einem Nachfolgeticket (besteht bereits) behandelt.

2023-08-09 10:31 UTC, huebnercl commented on isy-task/src/test/java/de/bund/bva/isyfact/task/TestTaskAuthentication.java
>      }
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-15 08:26 UTC, huebnercl approved these changes, later dismissed

2023-08-15 08:31 UTC, huebnercl approved these changes, later dismissed
all conversations are solved, by
- shifting to ISY-147
- investigating research outside this PR
- analysing testcases again after ISY-147
- decision and answering the commented questions

2023-09-05 08:50 UTC, huebnercl requested changes
Please update and merge this branch with master-branch including the new and approved isy-security component before further review actions

2023-09-08 08:23 UTC, tbribram commented on CHANGELOG.md
> +  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur Authentifizierung
fixed

2023-09-08 08:23 UTC, tbribram commented on isy-task/CHANGELOG.md
> +    * BREAKING CHANGE: Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations und für IsyTaskConfigurationProperties muss nur eine `registrationId` zur
fixed

2023-09-08 08:23 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public String getRegistrationId() { return registrationId; }
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        private String registrationId;
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/config/IsyTaskConfigurationProperties.java
> +        public void setRegistrationId(String registrationId) { this.registrationId = registrationId; }
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +    private final String registrationId;
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        this.registrationId = registrationId;
fixed

2023-09-08 08:24 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticator.java
> +        authentifizierungsmanager.authentifiziere(registrationId);
fixed

2023-09-08 08:25 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +            }
fixed

2023-09-08 08:25 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactory.java
> +                    defaultRegistrationId
fixed

2023-09-08 08:44 UTC, tbribram commented on isy-task/src/main/java/de/bund/bva/isyfact/task/monitoring/IsyTaskAspect.java
This matches the behavior in the old TaskKonfigurationVerwalter before the changes in IFS-2153.
There is not default value for the `deaktiviert` property: https://github.com/IsyFact/isyfact-standards/commit/98a22fc6#diff-95b98bc72fd6563c9d71d471ab79a97d8460e1cb143342d2028c5966f1dd846bL98-L103

If you think this is undesired behavior it might make sense to analyze this in a different ticket.

2023-09-08 08:45 UTC, tbribram commented on isy-task/src/test/java/de/bund/bva/isyfact/task/security/impl/IsySecurityAuthenticatorFactoryTest.java
> +    }
testcases will be reevaluated after merge

2023-09-08 08:47 UTC, tbribram commented on isy-task/src/test/resources/application-security-test.properties
> +spring.security.oauth2.client.registration.cc-testclient.provider=testrealm
related to test cases, will be reevaluated after merge

2023-09-08 09:08 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/isy-task/pages/nutzungsvorgaben/inhalt.adoc
Since this section of the documentation is about "another simple way to use isy-task" it doesn't really make sense to describe authentication.
I took a quick look over the documentation and there are other sections which should be updated (for example the properties `ausfuehrung`, `initial-delay` and `fixed-delay` are not configured via `isy.task` properties).

I'd propose looking over the documentation again in another ticket.

2023-09-08 09:10 UTC, tbribram commented
Incorporated the suggested changes.
Potential improvements to the tests and documentation will be reevaluated after merge.

2023-09-11 16:04 UTC, huebnercl requested changes
after checkout this branch it is not possible to build `isyfacts-standards` or especially `isy-security` and `isy-task` due to several errors for example in import-statements with `org.springframework` on missing classes or path in isy-security.

2023-09-12 07:15 UTC, tbribram commented
Since the Compile action finished without any problems (https://github.com/IsyFact/isyfact-standards/actions/runs/6120170282/job/16611483762?pr=42) and it also builds on my machine (just tested it again) I'd assume that this is a local problem on your machine.

Regardless it would help the process if you don't mark your question about local build problems as "requested changes" and instead provide an example (compiler output) that would help us analyze why it might not work on your machine.

2023-09-14 09:21 UTC, huebnercl approved these changes

2023-09-14 09:23 UTC, huebnercl commented
to resolve the still open conversations about reevaluation of testcases the ticket https://tracker.seitenbau.net/browse/ISY-385 was created.

2023-09-14 09:25 UTC, merged