IFS-2488: Paralleles Beibehalten von HTTP-Invoker
IsyFact/isyfact-standards pull request #45
Opened 2023-07-04 08:42 UTC by FabianPerl

Depends on #41

2023-08-01 08:22 UTC, huebnercl requested changes

2023-08-01 08:22 UTC, huebnercl commented on isy-serviceapi-core/src/main/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/DefaultCreateAufrufKontextToStrategy.java
> +        aufrufKontextTo.setDurchfuehrendeBehoerde(getStringValue(BHKNZ));
As in line 39 the StandardClaimNames exists for defining claimname constants, does it make sense or perhaps it still exists a class for the `isy-security-ClaimNames` constant definitions like for the `BHKNZ`?
It seems the usage and definition of `BHKNZ`  as hardcoded string or constant like in line 29 exists several times.

2023-08-01 08:22 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitTest.java
the combined coverage of the 3 testsuites
- `StelltLoggingKontextBereitAdvisorTest`
- `StelltLoggingKontextBereitAspectTest`
- `StelltLoggingKontextBereitTest`
does not cover:
- `StelltLoggingKontextBereitInterceptor.ermittleStelltLoggingKontextBereitAnnotation()` line 176 and 181-187

2023-08-01 08:22 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/autoconfigure/IsyServiceApiCoreAutoConfigurationSecurityTest.java
the coverage of this testsuite does not cover:
- IsyServiceApiCoreAutoConfiguration.stelltAufrufKontextBereitInterceptor() line 44-51
- IsyServiceApiCoreAutoConfiguration.stelltAufrufKontextBereitAdvisor() line 53-60

2023-08-01 08:22 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/FillAufrufKontextToTest.java
the combined coverage of the testsuites in package
`isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker`
does not cover:
- `IsyHttpInvokerClientInterceptor.afterPropertiesSet()` line 116 and 119 where required properties are missing
- `IsyHttpInvokerProxyFactoryBean.afterPropertiesSet()` line 67 where required property is missing
- `TimeoutWiederholungHttpInvokerRequestExecutor.doExecuteRequest()` line 112-115 the case TIMEOUT_WARTEZEIT_ABBRUCH

2023-08-01 08:22 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/FillAufrufKontextToTest.java
> +        tokenAttributes.put("bhknz", BHKNZ);
please use instead of hardcoded string - `roles`, `bhknz` - the constant definitions like the `StandardClaimNames` in the next lines and as it should be done on reading the token attributes in the code.

2023-08-09 10:37 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aop/StelltLoggingKontextBereitTest.java
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 10:39 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/autoconfigure/IsyServiceApiCoreAutoConfigurationSecurityTest.java
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-09 10:40 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/httpinvoker/FillAufrufKontextToTest.java
Testfälle werden nach dem Mergen erneut von msg untersucht und ggfs. ein Folgeticket erstellt.

2023-08-17 06:16 UTC, FabianPerl commented
The merge-base changed after approval, rebased Branch.

2023-09-05 12:58 UTC, huebnercl commented
Please update and merge this branch with master-branch including the new and approved isy-security component before further review actions

2023-09-08 08:25 UTC, FabianPerl commented
The merge-base changed after approval, rebased Branch.
Furthermore adds constants for testcase

2023-09-18 18:35 UTC, huebnercl requested changes
one comment about a failing testsuite.
if it makes sense and the reason for failure will not caused in the sourcecode of `isyfact-standards` but in the testsuite itself, we could approve this PR immediatly and shift the efforts to correct the testsuite in a following ticket like https://tracker.seitenbau.net/browse/ISY-385

2023-09-18 18:35 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aufrufkontext/TestConfig.java
The testsuite `AllgemeinerAufrufKontextInterceptorAnnotationTest` in the same directory fails in all testcases. 
See details in attached logfile:
[IFS-2488_Failed-Test_in_AllgemeinerAufrufKontextInterceptorAnnotationTest.log](https://github.com/IsyFact/isyfact-standards/files/12619875/IFS-2488_Failed-Test_in_AllgemeinerAufrufKontextInterceptorAnnotationTest.log)

2023-09-21 06:53 UTC, frgreiner commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aufrufkontext/TestConfig.java
@huebnercl 

I have no issues running all the tests without errors:
![grafik](https://github.com/IsyFact/isyfact-standards/assets/16579902/e7f4fce7-2020-45ba-9c10-87b121d9c411)
Based on the provided logfile, I assume that you have somehow deactivated/not activated the Maven profile JDK-17 workaround:
![grafik](https://github.com/IsyFact/isyfact-standards/assets/16579902/e4bec3d2-838f-4c89-9449-ef9b3c930843)

2023-09-21 09:57 UTC, huebnercl commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aufrufkontext/TestConfig.java
@frgreiner, @FabianPerl  

with several test constellations the following results occur:
- `jdk-11`, **active** `profile jdk-17-workaround`      => all tests successful
- `jdk-11`, **inactive** `profile jdk-17-workaround`   => all tests successful
- `jdk-18`, **active** `profile jdk-17-workaround`      => the testsuite AllgemeinerAufrufkontextInterceptorAnnotationTest fails
- `jdk-18`, **inactive** `profile jdk-17-workaround`   => the testsuite AllgemeinerAufrufkontextInterceptorAnnotationTest fails

it seems with `jdk-18` the maven build and tests should be improved
- either that all builds and tests will be successful
- or the maven build process will check for correct environment configurations and abort with expressive errror-messages
- than spending great efforts for researching in sourcecode and testcases

These efforts could be shifted in a following issue  as planed for further testcase researches like [[ISY-385] reevaluation of isy-task testcases after switch to isy-security - SEITENBAU-JIRA](https://tracker.seitenbau.net/browse/ISY-385)

2023-09-21 09:59 UTC, huebnercl approved these changes
with dependency and future efforts in followup issue https://tracker.seitenbau.net/browse/ISY-385

2023-09-22 08:11 UTC, frgreiner commented on isy-serviceapi-core/src/test/java/de/bund/bva/isyfact/serviceapi/core/aufrufkontext/TestConfig.java
@huebnercl siehe Dokumentation: [Allgemeine Produktvorgaben](https://isyfact.github.io/isyfact-standards-doku/latest/einstieg/produktkatalog/produktvorgabenAllgemein.html)
Für Bibliotheken ist die Vorgabe JDK 17 mit Language Level 8. Alles andere wird von uns nicht unterstützt.

2023-09-22 09:25 UTC, merged