IFS-1853: Umstellung isy-batchrahmen auf isy-security
IsyFact/isyfact-standards pull request #46
Opened 2023-07-04 09:08 UTC by FabianPerl

Depends on #41

2023-08-17 06:13 UTC, FabianPerl commented
The merge-base changed after approval, rebased Branch.

2023-09-05 08:48 UTC, huebnercl requested changes
Please update and merge this branch with master-branch including the new and approved isy-security component before further review actions

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * If the parameter is not set is set, the default value is returned.
```suggestion
     * If the parameter is not set, the default value is returned.
```

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be set or converted to a boolean.
converting a property of type string will always return a boolean, see javadoc of Boolean.parseBoolean:
`Parses the string argument as a boolean. The boolean returned represents the value true if the string argument is not null and is equal, ignoring case, to the string "true". Otherwise, a false value is returned, including for a null argument.
Example: Boolean.parseBoolean("True") returns true. Example: Boolean.parseBoolean("yes") returns false.
Params:
s – the String containing the boolean representation to be parsed
Returns:
the boolean represented by the string argument
Since:
1.5
`
=> the javadoc @throws does only return a `BatchrahmenKonfigurationException` if the property with parameter `name` does not exist.

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be converted to a boolean.
This method will never throw a `BatchrahmenKonfigurationException`, because if the property `name` does not exists, the default value of the correct type will be returned.

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/BatchRahmenEreignisSchluessel.java
> +        // hide ctor
confusing comment?

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/KonfigurationSchluessel.java
> +        // hide ctor
confusing comment?

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/KonfigurationSchluessel.java
> +     */
Copy-Paste Error of previous javadoc leads to wrong comment for this property here

2023-09-05 08:48 UTC, huebnercl commented on CHANGELOG.md
> +  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations. Batches müssen nur noch eine `registrationId` zur Authentifizierung bereitstellen. Die Meth
```suggestion
  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations. Batches müssen zur Indirektion auf die ClientRegistration nur noch eine `registrationId` für eine Authentifizierung bereitstellen. Die Methode `getAuthenticationCredentials` der `BatchAusfuehrungsBean` wurde entfernt.
```

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/CHANGELOG.md
> +  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations. Batches müssen nur noch eine `registrationId` zur Authentifizierung bereitstellen. Die Meth
```suggestion
  * Die Konfiguration von `benutzer`, `passwort` und `bhknz` erfolgt über isy-security ClientRegistrations. Batches müssen zur Indirektion auf die ClientRegistration nur noch eine `registrationId` für eine Authentifizierung bereitstellen. Die Methode `getAuthenticationCredentials` der `BatchAusfuehrungsBean` wurde entfernt.
```

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * If the parameter is not set is set, the default value is returned.
```suggestion
     * If the parameter is not set, the default value is returned.
```

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be converted to a string.
This method will never throw the Exception `BatchrahmenKonfigurationException`, because if the property `name`is not defined the default value `standardWert`will be returned. And if the property `name` is defined, it will be returned as string.

2023-09-05 08:48 UTC, huebnercl commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be set or converted to a boolean.
```suggestion
     * @throws BatchrahmenKonfigurationException If the configuration parameter is not set.
```
Following the javadoc of `Boolean.parseBoolean` it will always return a boolean value instead of throwing an exception:

`Parses the string argument as a boolean. The boolean returned represents the value true if the string argument is not null and is equal, ignoring case, to the string "true". Otherwise, a false value is returned, including for a null argument.`

2023-09-05 12:55 UTC, huebnercl commented
Please update and merge this branch with master-branch including the new and approved isy-security component before further review actions

2023-09-08 08:09 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * If the parameter is not set is set, the default value is returned.
fixed

2023-09-08 08:09 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be converted to a string.
throws removed from javadodc

2023-09-08 08:10 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * If the parameter is not set is set, the default value is returned.
fixed

2023-09-08 08:10 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be converted to a boolean.
throws removed from javadodc

2023-09-08 08:13 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konfiguration/BatchKonfiguration.java
> +     * @throws BatchrahmenKonfigurationException If the configuration parameter cannot be set or converted to a boolean.
fixed

2023-09-08 08:16 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/BatchRahmenEreignisSchluessel.java
> +        // hide ctor
I guess that was meant to be "constructor", replaced with more descriptive comment.

2023-09-08 08:16 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/KonfigurationSchluessel.java
> +        // hide ctor
I guess that was meant to be "constructor", replaced with more descriptive comment.

2023-09-08 08:17 UTC, tbribram commented on isy-batchrahmen/src/main/java/de/bund/bva/isyfact/batchrahmen/batch/konstanten/KonfigurationSchluessel.java
> +     */
fixed

2023-09-08 08:21 UTC, tbribram commented
Updates the PR with the suggested changes.

2023-09-08 11:14 UTC, evcimene approved these changes, later dismissed

2023-09-15 12:35 UTC, huebnercl approved these changes
...but with one open question, about the testcase with the annotation `@Secured` on class level instead of method level.
This kind of annotation should deny the invocation of the method `initialisieren` by an autorization on a dedicated right. But without a previous successfully processed authentification, which will be part of the ìnitialisieren`method, there is no initialized SecurityContext and no autorization possible.

2023-09-15 12:35 UTC, huebnercl commented on isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/GesicherterTestBatch2.java
> +@Secured("PRIV_Recht1")
As mentioned in the class description, an autorization will be performed before an authenticated SecurityContext with an `accesstoken` and set of role and rights was created and initialized.

But in the case of processing an autorization before a successull authentication the invocation of a secured method should be denied, which means the method `initialisieren` with the including authentication could never be processed.

2023-09-15 13:58 UTC, merged

2023-09-15 14:33 UTC, tbribram commented on isy-batchrahmen/src/test/java/de/bund/bva/isyfact/batchrahmen/batch/GesicherterTestBatch2.java
> +@Secured("PRIV_Recht1")
I'm not sure if the JavaDoc was correct to begin with.
This bean seems to be only used in a test case that tests batch execution with invalid roles (the privilege `PRV_Recht1` is never assigned to a role in isy-batchrahmen).
The annotation for this class used to be on the `initialisieren` method, but for this specific test case it doesn't matter whether it's applied on `initialisieren` or on class level.

I'd suggest reverting the annotation location and improving the JavaDoc as part of the follow up ticket to improve the current tests.