IFS-1887: Anpassung der Nutzungsvorgaben isy-security
IsyFact/isyfact-standards pull request #47
Opened 2023-07-04 09:22 UTC by FabianPerl

Depends on #42 & #46

2023-09-06 09:38 UTC, huebnercl requested changes
Please update and merge this branch with master-branch including the Ticket `ISY-147` with the new and approved isy-security component and adapt the documentation before further review actions

2023-09-06 09:38 UTC, huebnercl commented on CHANGELOG.md
> +- `IFS-1887`: [isyfact-standards-doc] Ergänzung der Nutzungsvorgaben für neuen Baustein Sicherheit
```suggestion
- `IFS-1887`: [isyfact-standards-doc] Ergänzung der Nutzungsvorgaben für neuen Sicherheitsbaustein `isy-security`
```

2023-09-06 09:38 UTC, huebnercl commented on CHANGELOG.md
Missing comments about ISY-147 changes with additional methods in AuthentifizierungsManager of isy-security for application-usage without 2AF by BHKNZ

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +|`registrationId` |Die ID der Client Registration aus `isy-security`, die zur Authentifizierung genutzt wird
missing comments about changes with ISY-147, especially here the renaming of the parameter `oaut2ClientRegistrationId`

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Enthält eine Anwendung mehrere Batches, so enthält sie auch mehrere BatchKonfigurationen und kann jeden Batch mit einer eigenen `registrationId` ausstatten.
renaming of parameter `registrationId` based on ISY-147

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Der Batchrahmen fordert von der BatchKonfiguration die Bereitstellung der `registrationId` zur ClientRegistration, um den Batch über den Baustein `isy-security` zu authentifizieren.
renaming of parameter `registrationId` based on ISY-147

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/changelog.adoc
Missing comments about ISY-147 changes with additional methods in `AuthentifizierungsManager` of isy-security for application-usage without 2AF by BHKNZ

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +NOTE: Es empfiehlt sich, die Beans direkt zu autowiren und das Interface hauptsächlich für eine Migration von isy-sicherheit zu verwenden.
```suggestion
NOTE: Es empfiehlt sich, die Beans direkt zu 'autowiren' und das Interface hauptsächlich für eine Migration vom alten Sicherheitsbaustein `isy-sicherheit` auf den neuen Baustein `isy-security` zu verwenden.
```

2023-09-06 09:38 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`Optional<Authentifizierungsmanager> getAuthentifizierungsManager()`:: Liefert ein `Optional`, das eine Referenz auf den `Authentifizierungsmanager` enthält, oder `null` falls die Anwendung als Resou
Der Typ Optional wurde mit ISY-147 wieder entfernt.

2023-09-13 06:00 UTC, FabianPerl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +`Optional<Authentifizierungsmanager> getAuthentifizierungsManager()`:: Liefert ein `Optional`, das eine Referenz auf den `Authentifizierungsmanager` enthält, oder `null` falls die Anwendung als Resou
As far as I can see, [the return value is still Optional.](https://github.com/IsyFact/isyfact-standards/blob/master/isy-security/src/main/java/de/bund/bva/isyfact/security/core/Security.java#L26)

2023-09-13 06:02 UTC, FabianPerl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Der Batchrahmen fordert von der BatchKonfiguration die Bereitstellung der `registrationId` zur ClientRegistration, um den Batch über den Baustein `isy-security` zu authentifizieren.
Variable was adjusted to `oauth2ClientRegistrationId` after rebase to master (including ticket ISY-147)

2023-09-13 06:03 UTC, FabianPerl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Enthält eine Anwendung mehrere Batches, so enthält sie auch mehrere BatchKonfigurationen und kann jeden Batch mit einer eigenen `registrationId` ausstatten.
Variable was adjusted to `oauth2ClientRegistrationId` after rebase to master (including Ticket ISY-147)

2023-09-25 15:37 UTC, huebnercl requested changes
the solution is quite near, simply some small reformulations...

2023-09-25 15:37 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Der Batchrahmen verwendet den Baustein `isy-security`, um den anfragenden Benutzer über einen der Authentifizierungswege Client Credential oder Ressource Owner Password (deprecated) via `oauth2Client
```suggestion
Der Batchrahmen verwendet den Baustein `isy-security`, um den in der Batch-Konfiguration via `oauth2ClientRegistrationId` definierten Benutzer über einen der Authentifizierungswege `Client Credential` oder `Ressource Owner Password Credential` (deprecated) zu authentifizieren.
```

2023-09-25 15:37 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +|`oauth2ClientRegistrationId` |Die ID der OAuth 2.0 Client Registration aus `isy-security`, die zur Authentifizierung genutzt wird
```suggestion
|`oauth2ClientRegistrationId` |Die ID der OAuth 2.0 Client Registration aus `isy-security`, die zur Authentifizierung genutzt wird. Die notwendigen Properties die für eine gültige `ClientRegistration` definiert werden müssen, sind in den Nutzungsvorgaben der Komponente `isy-security` beschrieben.
```

2023-09-25 15:37 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/blaupausen/pages/detailkonzept-komponente-batch/inhalt.adoc
> +Der Batchrahmen fordert von der BatchKonfiguration die Bereitstellung der `oauth2ClientRegistrationId` zur ClientRegistration, um den Batch über den Baustein `isy-security` zu authentifizieren.
```suggestion
Der Batchrahmen fordert, dass in der BatchKonfiguration zur Batch spezifischen `Batch-ID` das neue Property `oauth2ClientRegistrationId` hinzugefügt wird, dessen Wert als Indirektion auf eine `ClientRegistration` führt, um den Batch über den Baustein `isy-security` zu authentifizieren.
```

2023-09-27 09:10 UTC, FabianPerl commented
@huebnercl 

I rebased the branch and commited the requested changes. Hope it fits!

2023-09-27 12:11 UTC, huebnercl approved these changes

2023-09-28 08:40 UTC, merged