feature/ifs 3821 ergänzung zweier issuer ur ls in dokumentation isy security (rel3.x)
IsyFact/isyfact-standards pull request #476
Opened 2024-07-05 09:43 UTC by huebnercl

2024-07-09 10:20 UTC, dauna-msg requested changes

2024-07-09 10:20 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +==== Problematik per interner oder externer URL
Überschrift: "Aufruf des IAM-Systems über unterschiedliche URLs"

Und bitte einmal genau pürfen, ob wir von URL oder URI sprechen und wie Seitenbau dies handhabt. Hier sollten wir einheitlich sein.

2024-07-09 10:20 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Sofern das IAM über zwei unterschiedliche URLs aufgerufen wird, müssen beide URLs der Anwendung, für die die Autorisierung erlangt wird, bekannt sein.
Hier bitte nicht nur auf zwei begrenzen. "Sofern das IAM-System über unterschiedliche URLs...... müssen alle URLs....".

2024-07-09 10:20 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Wie kann nun dieser Problematik per Konfiguration begegenet werden?
Die einzelnen Konfigurationsparameter im Folgenden würde ich entfernen, sie kommen in die Nutzungsvorgaben.

Lösung:
Um in der Anwendung Access-Tokens erfolgreich zu validieren, die über eine in der Anwendung abweichend konfigurierte IAM-URL ausgestellt wurden, müssen alle genutzten URLs des IAM-Systems in der Anwendung hinterlegt werden. Dies geschieht über die Anwendungskonfiguration. Auf diese Weise können beliebig viele URLs konfiguriert werden.

2024-07-09 10:20 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Sofern das IAM über zwei unterschiedliche URLs aufgerufen wird, müssen beide URLs der Anwendung, für die die Autorisierung erlangt wird, bekannt sein.
Bitte noch Abbildung einfügen.
![Uploading unterschiedliche-issuerURIs.dn.svg…]()

2024-07-11 05:30 UTC, dauna-msg requested changes

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/changelog.adoc
> +// tag::release-3.0.0[]
Der Tag müsste doch 3.1.0 heißen?

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +==== Aufruf des IAM-Systems über unterschiedliche URIs
Bitte einheitlich "URI" verwenden und nicht mehr "URL".

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Wenn in einer Anwendungslandschaft das IAM über mehrere unterschiedliche URLs aufgerufen werden kann, dann benötigt eine Anwendung mindestens eine bis alle dieser URIs, um eine Authentifizierung mit
Für die Authentifizierung reicht eine URI, für die Tokenvalidierung können mehrere benötigt werden.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Dies ist zum Beispiel der Fall, wenn eine interne URI des IAM für Aufrufe von innerhalb der Anwendungslandschaft und eine externe URI für Aufrufe von außerhalb der Anwendungslandschaft benötigt werde
Bitte immer nur einen Satz pro Zeile.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Wird jetzt allerdings, wie beispielsweise bei einer Authentifizierung über das _Portal_, in der `issuer-uri` eine *externe* URL benötigt, damit eine _externe Anwendung_ den _IAM/KeyCloak_ überhaupt v
"Keycloak" bitte entfernen.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +wobei die `tenant-id` einzig als Gruppierungskriterium für die beiden Properties `issuer-uri` und `jwk-set-uri` eingesetzt wird. Somit kann diese beispielsweise mit fachlich aussagekräftigen Namen, w
Bitte nur ein Satz pro Zeile.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Sobald also beide Properties für einen Mandant gesetzt sind, dann wird der Wert von `issuer-uri` für den Aufruf auf den Authentifizierungsserver des IAM verwendet, insbesonderen für *externe* Aufrufe
Mein Verständnis und auch so, wie es SB/Materna beschrieben haben, ist es genau umgekehrt. Also issuer-uri: Wird zur Validierung des iss-claims verwendet. jwk-set-uri: Wird zur Erlangen der Zertifikatsdateien verwendet.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +tenants.*portal*.jwk-set-uri| Property-Set zur Definition einer *externen* und *internen* IAM-URL für den Mandant *Portal*
Ich würde das hier generell nicht interne/externe URI an dieser Stelle nennen. 
Sondern eher: 
1. Parameter = Abgleich mit URI aus Token
2. Parameter = Kommunikation mit dem IAM / Zertifikatsabruf

Und Beispiele wären gut, da kannst du dich an SB/Materna orientieren: https://github.com/IsyFact/isyfact-standards/pull/473/files#diff-aedaf1b4a803dd5aa46ad0c7159d0a3ba7d227017fbbc6591917391872463bb7

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Aber würde eine *interne* _ServiceBean_ bei der _Token-Validierung_ eine *externe* URI auf den *internen* _Authentifizierungsserver_ des IAM verwenden, dann würde dies sicherlich nicht funktionieren.
Was meinst du hier mit "Service-Bean"? Und ich würde de Satz umschreiben, indem ich das "würde" entferne.

2024-07-11 05:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Gegebenenfalls erweitert KeyCloak intern bei der Token-Validierung die  `jwk-set-uri` um den Standard-Pfad von KeyCloak `protocol/openid-connect/certs` um das notwendige Zertifikat zu ermitteln.
Bitte nicht Keycloak verwenden.

2024-07-11 15:43 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/changelog.adoc
> +// tag::release-3.0.0[]
ja wurde korrigiert

2024-07-11 15:50 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +==== Aufruf des IAM-Systems über unterschiedliche URIs
wurde über alle Änderungen des Tickets ersetzt.

2024-07-11 16:04 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Wenn in einer Anwendungslandschaft das IAM über mehrere unterschiedliche URLs aufgerufen werden kann, dann benötigt eine Anwendung mindestens eine bis alle dieser URIs, um eine Authentifizierung mit
ja das ist korrekt, daher wurde umformuliert auf "vollständige Authentifizierung inklusive darauffolgender Tokenvalidierung und Autorisierung"

2024-07-11 16:05 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Dies ist zum Beispiel der Fall, wenn eine interne URI des IAM für Aufrufe von innerhalb der Anwendungslandschaft und eine externe URI für Aufrufe von außerhalb der Anwendungslandschaft benötigt werde
Sorry, ja das wurde angepasst

2024-07-11 16:10 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +wobei die `tenant-id` einzig als Gruppierungskriterium für die beiden Properties `issuer-uri` und `jwk-set-uri` eingesetzt wird. Somit kann diese beispielsweise mit fachlich aussagekräftigen Namen, w
wurde geändert.

2024-07-11 16:27 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +tenants.*portal*.jwk-set-uri| Property-Set zur Definition einer *externen* und *internen* IAM-URL für den Mandant *Portal*
Das scheint so nicht ganz korrekt zu sein.
1. Parameter issuer-uri = Aufruf des IAM / ohne `jwk-set-uri` auch für Token-Abgleich und Zertifikatsabruf
2. Parameter jwk-set-uri = sobald gesetzt erfolgt mit dieser URI der TokenAbgleich und der Zertifikatsabruf

Beispiele wurden bewusst vermieden, aber eine Referenz auf die Beispiele von SB/M wurde nach der Tabelle eingefügt

2024-07-11 16:29 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Wird jetzt allerdings, wie beispielsweise bei einer Authentifizierung über das _Portal_, in der `issuer-uri` eine *externe* URL benötigt, damit eine _externe Anwendung_ den _IAM/KeyCloak_ überhaupt v
gelöscht

2024-07-11 16:31 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Aber würde eine *interne* _ServiceBean_ bei der _Token-Validierung_ eine *externe* URI auf den *internen* _Authentifizierungsserver_ des IAM verwenden, dann würde dies sicherlich nicht funktionieren.
Service-Bean auf Geschäftsanwendung geändert und den Konjunktiv heraus genommen.

2024-07-11 16:36 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Sobald also beide Properties für einen Mandant gesetzt sind, dann wird der Wert von `issuer-uri` für den Aufruf auf den Authentifizierungsserver des IAM verwendet, insbesonderen für *externe* Aufrufe
SB/M schreibt:
issuer-uri = URI des Ausstellers des JWT, spezifisch für den Tenant
jwk-set-uri = URI des JWK-Sets, das die öffentlichen Schlüssel bereitstellt, welche zur Validierung der JWT-Signatur verwendet werden

wo liest du darin eine umgekehrte Bedeutung heraus, als wie ich sie beschrieben habe?

2024-07-11 17:08 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +==== Problematik per interner oder externer URL
Alles auf URI umbenannt.

2024-07-11 17:09 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Sofern das IAM über zwei unterschiedliche URLs aufgerufen wird, müssen beide URLs der Anwendung, für die die Autorisierung erlangt wird, bekannt sein.
wie gewünscht umgesetzt

2024-07-11 17:10 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Gegebenenfalls erweitert KeyCloak intern bei der Token-Validierung die  `jwk-set-uri` um den Standard-Pfad von KeyCloak `protocol/openid-connect/certs` um das notwendige Zertifikat zu ermitteln.
geändert

2024-07-11 17:11 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Wie kann nun dieser Problematik per Konfiguration begegenet werden?
wie gewünscht geändert

2024-07-15 12:30 UTC, dauna-msg requested changes

2024-07-15 12:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/changelog.adoc
> +
Ich erhalte ganz oben immer noch den Hinweis mit ungültigen Zeichen im Branchnamen: 

The head ref may contain hidden characters: "feature/IFS-3821_Erg\u00E4nzung_Zweier_Issuer-URLs_in_Dokumentation_isy-security-(rel3.x)"

2024-07-15 12:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +tenants.*portal*.jwk-set-uri| Property-Set zur Definition einer *externen* und *internen* IAM-URI für den Mandant *Portal*
Bitte immer "Tenant" verwenden und nicht "Mandant".

2024-07-15 12:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +.Property-Pfad-Beispiele für Multi IAM-URIs
Ich würde hier weiterhin nicht zwischen "interner" und "externer" URI unterscheiden. Ich hatte ja in einem meiner letzten Kommentare schon einen Verbesserungsvorschlag kommentiert.

2024-07-15 12:30 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Das Property `issuer-uri` wird im Normalfall - für die Rolle der _"Authentifizierung startenden Anwendung"_- mit der URI des _Authentifizierungsservers_ des IAM initialisiert.
Nein, in diesem Fall wird der Konfigurationsparamter "client.provider.<providerId>.issuer-uri" verwendet. Weder über "tenants....issuer-uri", noch über "tenants...jwk-set-uri" wird eine Authentifizierung angestoßen.

2024-07-15 17:38 UTC, closed without merging