Add GitHub Action for Maven Build
IsyFact/isyfact-standards pull request #48
Opened 2023-07-04 09:41 UTC by tobias-schmitz

2023-07-24 13:23 UTC, vonLogaJ requested changes

2023-07-24 13:23 UTC, vonLogaJ commented on .github/workflows/maven.yml
> +        continue-on-error: true
Kann das entfernt werden?

2023-07-24 13:23 UTC, vonLogaJ commented on .github/workflows/maven.yml
> +        run: mvn compile $MAVEN_CLI_OPTS -Dcheckstyle.skip
Optionen sollten immer vor den goals / phases stehen:
mvn [options] [<goal(s)>] [<phase(s)>]
https://maven.apache.org/run.html

```suggestion
        run: mvn $MAVEN_CLI_OPTS -Dcheckstyle.skip compile
```

2023-07-24 13:23 UTC, vonLogaJ commented on .github/workflows/maven.yml
> +        run: mvn test $MAVEN_CLI_OPTS -Dcheckstyle.skip
Optionen sollten immer vor den goals / phases stehen:
mvn [options] [<goal(s)>] [<phase(s)>]
```suggestion
        run: mvn $MAVEN_CLI_OPTS -Dcheckstyle.skip test
```

2023-07-24 13:23 UTC, vonLogaJ commented on .github/workflows/maven.yml
> +        run: mvn checkstyle:checkstyle-aggregate $MAVEN_CLI_OPTS
Optionen sollten immer vor den goals / phases stehen:
mvn [options] [<goal(s)>] [<phase(s)>]
```suggestion
        run: mvn $MAVEN_CLI_OPTS checkstyle:checkstyle-aggregate
```

2023-07-24 13:23 UTC, vonLogaJ commented on .github/workflows/maven.yml
> +        run: mvn compile spotbugs:check $MAVEN_CLI_OPTS -Dcheckstyle.skip -Denforcer.skip -Dtidy.skip
```suggestion
        run: mvn $MAVEN_CLI_OPTS -Dcheckstyle.skip -Denforcer.skip -Dtidy.skip compile spotbugs:check
```

2023-07-24 13:23 UTC, vonLogaJ commented on isyfact-standards-bom/pom.xml
> +        <isy-serviceapi-sst.version>1.9.0</isy-serviceapi-sst.version>
Warum wird hier nicht auch die 1.10.0 genutzt?
```suggestion
        <isy-serviceapi-sst.version>1.10.0</isy-serviceapi-sst.version>
```

2023-07-25 07:12 UTC, tobias-schmitz commented on .github/workflows/maven.yml
> +        continue-on-error: true
Genau, das wird nicht mehr benötigt, da der Checkstyle-Step nicht mehr fehlschlagen sollte. Wurde entfernt.

2023-07-25 07:12 UTC, tobias-schmitz commented on .github/workflows/maven.yml
> +        run: mvn compile $MAVEN_CLI_OPTS -Dcheckstyle.skip
Wurde angepasst.

2023-07-25 07:12 UTC, tobias-schmitz commented on .github/workflows/maven.yml
> +        run: mvn checkstyle:checkstyle-aggregate $MAVEN_CLI_OPTS
Wurde angepasst.

2023-07-25 07:13 UTC, tobias-schmitz commented on .github/workflows/maven.yml
> +        run: mvn compile spotbugs:check $MAVEN_CLI_OPTS -Dcheckstyle.skip -Denforcer.skip -Dtidy.skip
Wurde angepasst.

2023-07-25 07:13 UTC, tobias-schmitz commented on isyfact-standards-bom/pom.xml
> +        <isy-serviceapi-sst.version>1.9.0</isy-serviceapi-sst.version>
Die habe ich wohl übersehen. Version 1.10.0 wird jetzt verwendet.

2023-07-25 07:13 UTC, tobias-schmitz commented on .github/workflows/maven.yml
> +        run: mvn test $MAVEN_CLI_OPTS -Dcheckstyle.skip
Wurde angepasst.

2023-07-25 13:37 UTC, vonLogaJ approved these changes

2023-07-25 13:44 UTC, merged