[Sprint 110] IFS-2395 messageSourceHolder 3.x
IsyFact/isyfact-standards pull request #543
Opened 2024-08-27 13:32 UTC by sb-sfink

* chore(util): IFS-2395 translates javadoc
* feat(util): IFS-2395 makes RecursiveToStringBuilder constructor private
* docs(util): IFS-2395 adds deprecation for MessageSourceHolder and MessageSourceFehlertextProvider
* feat(util): IFS-2395 adds override annotation in MessageSourceFehlertextProvider
* feat: IFS-2395 adds entry to CHANGELOG.md

2024-08-28 08:36 UTC, frgreiner commented
Hinweis für die Technische Abnahme: Es ist bei diesem PR das Ziel die entsprechenden Klassen als `@Deprecated` zu markieren und das deshalb fehlschlagende Quality Gate sollte die Abnahme nicht verhindern!

2024-09-20 13:39 UTC, mtpham-collab requested changes

2024-09-20 13:39 UTC, mtpham-collab commented on isyfact-standards-doc/src/docs/antora/modules/isy-util/pages/nutzungsvorgaben/inhalt.adoc
> +Für die Benennung der `MessageSource`-Bean wird empfohlen, einen eindeutiger Namen zu wählen, damit diese via Spring-Boardmittel überschrieben werden kann.
```suggestion
Für die Benennung der `MessageSource`-Bean wird empfohlen, einen eindeutigeren Namen zu wählen, damit diese mittels Spring-Bordmitteln überschrieben werden kann.

2024-09-30 18:33 UTC, msg-Tomaszewski approved these changes, later dismissed

2024-10-01 16:53 UTC, mtpham-collab approved these changes

2024-10-01 16:54 UTC, merged