[Sprint 110] IFS-2395 messageSourceHolder
IsyFact/isyfact-standards pull request #546
Opened 2024-08-28 11:21 UTC by sb-sfink

* feat(task): IFS-2395 hides constructor for static content
* chore(task): IFS-2395 translates javadoc
* refactor(task): IFS-2395 removes suffix 'de' in message files
* feat(task): IFS-2395 removes MessageSourceHolder

    * declares springs MessageSource

* test(task): IFS-2395 adapts testcases
* chore(task): IFS-2395 adds entry to CHANGELOG.md
* chore: IFS-2395 adds override annotation for FehlertextProvider
* docs: IFS-2395 describes migration from MessageSourceHolder and MessageSourceFehlertextProvider
* docs: IFS-2395 changes Fehler-ID to Ausnahme-ID
* docs: IFS-2395 adapts tutorial
* docs: IFS-2395 fixes FehlertextProvider paragraph

2024-09-20 13:35 UTC, mtpham-collab requested changes

2024-09-20 13:35 UTC, mtpham-collab commented on isyfact-standards-doc/src/docs/antora/modules/einstieg/pages/tutorial/inhalt.adoc
> +`isy-exception-core` enthält abstrakte Exception-Klassen und Interfaces die in Anwendungen zu verwenden sind.
```suggestion
`isy-exception-core` enthält abstrakte Exception-Klassen und Interfaces, die in Anwendungen zu verwenden sind.

2024-09-20 13:35 UTC, mtpham-collab commented on isyfact-standards-doc/src/docs/antora/modules/isy-util/pages/nutzungsvorgaben/inhalt.adoc
> +Für die Benennung der `MessageSource`-Bean wird empfohlen, einen eindeutiger Namen zu wählen, damit diese via Spring-Boardmittel überschrieben werden kann.
```suggestion
Für die Benennung der `MessageSource`-Bean wird empfohlen, einen eindeutigeren Namen zu wählen, damit diese mittels Spring-Bordmitteln überschrieben werden kann.

2024-09-20 13:35 UTC, mtpham-collab commented on isyfact-standards-doc/src/docs/antora/modules/release/pages/migrationsleitfaden.adoc
> +Wenn Bedarf zur Anpassung der Nachrichten besteht, muss die jeweilige `MessageSource`-Bean via Spring-Bordmittel überschrieben werden.
```suggestion
Wenn Bedarf zur Anpassung der Nachrichten besteht, muss die jeweilige `MessageSource`-Bean mittels Spring-Bordmitteln überschrieben werden.

2024-09-30 18:31 UTC, msg-Tomaszewski approved these changes

2024-10-15 14:22 UTC, msg-Tomaszewski approved these changes

2024-10-15 14:27 UTC, msg-Tomaszewski approved these changes

2024-10-29 14:47 UTC, msg-Tomaszewski approved these changes

2024-10-29 14:53 UTC, mtpham-collab approved these changes

2024-10-29 14:54 UTC, merged