ISY-54: migration guide for switching to isy-security
IsyFact/isyfact-standards pull request #66
Opened 2023-08-22 14:14 UTC by tbribram

2023-09-26 13:19 UTC, huebnercl requested changes

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +Jede Instanz soll durch einen sprechenden und eindeutigen `provider-name` bzw. eine `registration-id` ersetzt werden.
```suggestion
Jede Instanz soll durch einen sprechenden und eindeutigen `provider-name` bzw. eine `oauth2ClientRegistrationId` ersetzt werden.
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.resource`|`.registration.<registration-id>.client-id`|
```suggestion
|`.resource`|`.registration.<registration-id>.client-id`| Authentifizierungsdaten für den neuen `client-credential`-Flow
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.credentials-secret`|`.registration.<registration-id>.client-secret`|
```suggestion
|`.credentials-secret`|`.registration.<registration-id>.client-secret`| Authentifizierungsdaten für den neuen `client-credential`-Flow
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`.registration.<registration-id>.authorization-grant-type=password`| neu, da ein zusätzlicher OAuth Flow unterstützt wird
```suggestion
|-|`.registration.<registration-id>.authorization-grant-type=password`| neu, da ein zusätzlicher OAuth Flow unterstützt wird. Der Wert `password` entspricht dem bisherigen Flow in isy-sicherheit.
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The properties `username` and `password` are only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects the _authentication properties_ on a dedicated path. This means the previous defined properties `username` and `password` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get these values as parameters through external application invocations. In these cases _isy-security_ will transfer the _authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.username`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `username`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The properties `username` and `password` are only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects the _authentication properties_ on a dedicated path. This means the previous defined properties `username` and `password` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get these values as parameters through external application invocations. In these cases _isy-security_ will transfer the _authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.password`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `password`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The property `bhknz` is only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects this _properties_ on a dedicated path. This means the previous defined property `bhknz` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get this value through external application invocations out of a _client-certificate_ transfered in the HTTP-Header. In these cases _isy-security_ will transfer the _2FA-authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.bhknz`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `bhknz`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-26 13:19 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +** Die Methode `getBerechtigungsmanager()` gibt Zugang zum Interface `Berechtigungsmanager`, über das das Bearer Token verarbeitet kann.
```suggestion
** Die Methode `getBerechtigungsmanager()` gibt Zugang zum Interface `Berechtigungsmanager`, über das das Bearer Token verarbeitet wird. /werden kann.
```

2023-09-28 06:33 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +Jede Instanz soll durch einen sprechenden und eindeutigen `provider-name` bzw. eine `registration-id` ersetzt werden.
This section describes the name of the Spring property.
This part of the migration guide is also pretty clear about it being a `spring.oauth2.client.registration` properties, avoiding possible confusion with other application IDs.

2023-09-28 06:36 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.resource`|`.registration.<registration-id>.client-id`|
The client ID is required for the Resource Owner Credentials Flow (and other flows) as well.
Since the property has an exact match to the previous property from `isy-sicherheit-keycloak` users should be familiar with it.

2023-09-28 06:37 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.credentials-secret`|`.registration.<registration-id>.client-secret`|
see above

2023-09-28 06:39 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`.registration.<registration-id>.authorization-grant-type=password`| neu, da ein zusätzlicher OAuth Flow unterstützt wird
Good suggestion!

2023-09-28 06:58 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +** Die Methode `getBerechtigungsmanager()` gibt Zugang zum Interface `Berechtigungsmanager`, über das das Bearer Token verarbeitet kann.
Probably gonna reword this one completely, since the interface can't process the token in a way that changes it but only offers easy access to its properties.

2023-09-28 08:58 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
Focusing on the actual migration of existing properties, this replaces individual application configuration that used fixed credentials to later create an `AufrufKontext` and authenticate it.
Since we can't know how the application managed or created these properties the description should be limited to the fact that these replace application specific configuration parameters.

2023-10-05 15:33 UTC, huebnercl requested changes

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +Jede Instanz soll durch einen sprechenden und eindeutigen `provider-name` bzw. eine `registration-id` ersetzt werden.
We should follow the design matchings we made in several meetings in the past.
In all other migration guide or usage documents like batch and task these decisions were obeyed as the following snippes shows:

from the task migration guide:
--

...
[[task-properties-isy-security]]
**.Properties mit isy-security in IsyFact 3**

[source,properties]

`isy.task.tasks.halloWeltTask.`**`oauth2ClientRegistrationId`**`=TestClient`
...

from batch usage guid:
----

...
**.Die Eigenschaften des Batchbenutzers**

|Property |Beschreibung
|**`oauth2ClientRegistrationId`** |Die ID der OAuth 2.0 Client Registration aus `isy-security`, die zur Authentifizierung genutzt wird.
Die notwendigen Properties die für eine gültige `ClientRegistration` definiert werden müssen, sind in den Nutzungsvorgaben der Komponente `isy-security` beschrieben.
...


Reason
---
The confusion in the early discussions and reviews was always the wording `registration-id`, which will not be as expressive as expected. Which Identifier does it mean: 
- the instance identifier
- the application identifier 
- or the `spring client registration` identifier?

That's the reason why we made the decision to use the more expressive word `oauth2ClientRegistrationId`, which is introduced in the most other documents. 

So please let use keep them unique.

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.resource` |`.registration.<registration-id>.client-id` |
```suggestion
|`.resource` |`.registration.<registration-id>.client-id` |Neu, Authentifizierungsidentifier der _ConfidentialClient_-Applikation im Autorisierungsserver.
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.credentials-secret` |`.registration.<registration-id>.client-secret` |
```suggestion
|`.credentials-secret` |`.registration.<registration-id>.client-secret` | Neu, Authentifizierungs-Secret, das nur der ConfidentialClient-Anwendung und dem Autorisierungsserver bekannt ist.
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|- |`isy.security.oauth2.registration.<registration-id>.username` |Neu, ersetzt Authentifizierungsdaten die vorher individuell pro Anwendung konfiguriert wurden und benutzt wurden, um einen AufrufKon
```suggestion
|- |`isy.security.oauth2.registration.<registration-id>.username` |Neu, für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `username`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|- |`isy.security.oauth2.registration.<registration-id>.password` |Neu, ersetzt Authentifizierungsdaten die vorher individuell pro Anwendung konfiguriert wurden und benutzt wurden, um einen AufrufKon
```suggestion
|- |`isy.security.oauth2.registration.<registration-id>.password` |Neu,  für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `password`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|- |`isy.security.oauth2.registration.<registration-id>.bhknz` |Neu, ersetzt Authentifizierungsdaten die vorher individuell pro Anwendung konfiguriert wurden und benutzt wurden, um einen AufrufKontex
```suggestion
|- |`isy.security.oauth2.registration.<registration-id>.bhknz` |Neu, für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `bhknz`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +** Die Methode `getAuthentifizierungsmanager()` ermöglicht Zugang zum Interface `Authentifizierungsmanager`, über das eine Authentifizierung mit dem konfigurierten OpenID Connect Provider (bspw. Keyc
```suggestion
** Die Methode `getAuthentifizierungsmanager()` liefert das Interface `Authentifizierungsmanager` zurück, über dessen Implementierung dann eine Authentifizierung mit dem konfigurierten OpenID Connect Provider (bspw. Keycloak) durchgeführt werden kann.
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +** Die Methode `getBerechtigungsmanager()` ermöglicht Zugang zum Interface `Berechtigungsmanager`, über das auf die im Bearer Token enthaltenen Informationen zugegriffen werden kann.
```suggestion
** Die Methode `getBerechtigungsmanager()` liefert das Interface `Berechtigungsmanager` zurück, über dessen Implementierung dann auf die im _Bearer Token_ enthaltenen _Autorisierungsinformationen_ zugegriffen werden kann.
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +Konkret bietet das Interface `Berechtigungsmanager` Methoden an, um Berechtigungen und Rollen abzufragen (siehe xref:isy-security:nutzungsvorgaben/inhalt.adoc#attr-token-abfragen[Nutzungsvorgaben isy
```suggestion
Konkret sind in dem Interface `Berechtigungsmanager` Methoden definiert, über dessen Implementierung Berechtigungen und Rollen abgefragt werden können (siehe xref:isy-security:nutzungsvorgaben/inhalt.adoc#attr-token-abfragen[Nutzungsvorgaben isy-security]).
```

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.resource`|`.registration.<registration-id>.client-id`|
please see new suggestion below

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|`.credentials-secret`|`.registration.<registration-id>.client-secret`|
please see new suggestion below

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
please see new suggestion below

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +** Die Methode `getBerechtigungsmanager()` gibt Zugang zum Interface `Berechtigungsmanager`, über das das Bearer Token verarbeitet kann.
please see new suggestion below

2023-10-05 15:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
please see new suggestion below

2023-10-06 08:42 UTC, huebnercl approved these changes

2023-10-06 12:06 UTC, dauna-msg approved these changes

2023-10-06 12:07 UTC, merged