ISY-183 Migrationsleitfaden ergaenzen Bridgemodule
IsyFact/isyfact-standards pull request #67
Opened 2023-08-24 07:03 UTC by dkurowski-materna

2023-10-05 08:11 UTC, kollmana approved these changes, later dismissed
Can not review picture IFS3_calls.dn.png due to problems with LFS

2023-10-06 08:02 UTC, kollmana approved these changes, later dismissed
Can not review picture IFS3_calls.dn.png due to problems with LFS

2023-10-06 09:50 UTC, huebnercl requested changes
however found some small changes/suggestions...

2023-10-06 09:50 UTC, huebnercl commented on CHANGELOG.md
> +- [isyfact-standards-doc] Migrationsleitfaden zur Entfernung der Bridge-Module
```suggestion
- `ISY-183`: [isyfact-standards-doc] Migrationsleitfaden zur Entfernung der Bridge-Module
```

2023-10-06 09:50 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +Dabei ist zu beachten, dass zwei der Ersatzmodule in IsyFact 1-Versionen verwendet werden.
```suggestion
Dabei ist zu beachten, dass zwei der Ersatzmodule eine Abhängigkeit zu IsyFact-1.x haben.
```

2023-10-09 07:19 UTC, as-materna commented
@huebnercl accepted suggestions and resolved conflicts. Please approve and merge.

2023-10-09 09:07 UTC, huebnercl approved these changes

2023-10-09 09:07 UTC, merged