[Sprint 78] IFS-2561 optionale rollenrechte
IsyFact/isyfact-standards pull request #74
Opened 2023-08-29 11:18 UTC by FabianPerl

2023-09-04 14:01 UTC, kollmana requested changes
Code:
- not-existing resource file: exception or at leat log entry
- Tests for error cases (resources file not found, not readable, contains no AnwedungsId)
Documentation:
- Effect of not existing role-rights mapping

-

2023-09-04 14:01 UTC, kollmana commented on isy-security/src/main/java/de/bund/bva/isyfact/security/xmlparser/RolePrivilegesMapper.java
> +        if (roleMappingXmlResource.exists()) {
RolePrivilegesMappingException("Could not find role privileges mapping file") got lost. 
 When the role mapping  (and thus the RolePrivilegesMappingFile) is optional, I would expect the ClassPathResource to be non-existent or null. But this case is not handled either. 
At least, I would expect a log entry, telling that 'no role privileges mapping file was found'.

2023-09-04 14:01 UTC, kollmana commented on isy-security/src/test/java/de/bund/bva/isyfact/security/authentication/RolePrivilegesMapperTest.java
> +class RolePrivilegesMapperTest {
No tests for error cases / exceptions (resource file not found, not readable, does not contain AnwendungsId)

2023-09-04 14:01 UTC, kollmana commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Im Falle einer nicht vorhandenen Datei verbleibt die Liste der Rollen und Rechte unverändert, d. h. es werden keine standardmäßigen Zuweisungen vorgenommen.
What is the effect, what is the contents of the list of roles & rights, when it 'remains unchanged' ("verbleibt die Liste der Rollen und Rechte unverändert")?
Is it empty and there are none application specific rights?
In that case, the application services can not be secured by @Secured.

2023-09-08 09:13 UTC, FabianPerl commented on isy-security/src/test/java/de/bund/bva/isyfact/security/authentication/RolePrivilegesMapperTest.java
> +class RolePrivilegesMapperTest {
Added a test case that checks for throwing an exception if ApplicationID is empty (if file exists). There is already a test that checks if file was not found, but added verification for log entry

2023-09-08 09:15 UTC, FabianPerl commented on isy-security/src/main/java/de/bund/bva/isyfact/security/xmlparser/RolePrivilegesMapper.java
> +        if (roleMappingXmlResource.exists()) {
Documentation adjusted so that it is more apparent. There are applications that do not actively secure interfaces, where a rollenrechte.xml was previously specified without actively using it..

2023-09-08 09:15 UTC, FabianPerl commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/nutzungsvorgaben/inhalt.adoc
> +Im Falle einer nicht vorhandenen Datei verbleibt die Liste der Rollen und Rechte unverändert, d. h. es werden keine standardmäßigen Zuweisungen vorgenommen.
the documentation should make this more obvious now

2023-09-08 09:16 UTC, FabianPerl commented
Rebased Branch and answered the comments

2023-09-12 12:54 UTC, kollmana commented on isy-security/src/test/java/de/bund/bva/isyfact/security/authentication/RolePrivilegesMapperTest.java
> +class RolePrivilegesMapperTest {
OK

2023-09-12 12:56 UTC, kollmana commented on isy-security/src/main/java/de/bund/bva/isyfact/security/xmlparser/RolePrivilegesMapper.java
> +        if (roleMappingXmlResource.exists()) {
OK

2023-09-12 12:58 UTC, kollmana approved these changes

2023-09-13 14:09 UTC, merged