Feature/ifs 2596 endredaktion und aenderungen dokumentation
IsyFact/isyfact-standards pull request #92
Opened 2023-09-13 09:26 UTC by msg-ptavoul

2023-09-13 09:39 UTC, dauna-msg requested changes

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/security-schnittstellen.dn.svg
Diese Abbildung bitte entfernen bzw. mit der aktuellen aus dem Master ersetzen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Innerhalb des Anwendungskerns eines IT-Systems wird das `JWT Access-Token` weitergegeben. Zur Stärkung der Vertrauenswürdigkeit wird jedes `JWT Access-Token` beim Eintritt in ein IT-System auf Gült
"Innerhalb der Anwendungslandschaft..."

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Eine Zweifaktor-Authentifizierung ist durch das Behördenkennzeichen (BhKnz) als zusätzliches Authentifizierungsmerkmal konzipiert, allerdings setzt dies im IAM-Service voraus, dass dieses Merkmal d
Bitte vorherige Version benutzen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Die Authentifizierung und grobgranulare Autorisierung (mittels des Nutzers zugeordneten Rollen) erfolgt an den Außenschnittstellen der Systemlandschaft (Portal, Authentication-Gateway bzw. Service-
Bitte vorherige Version nutzen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Hierbei übermittelt der Benutzer seine Authentifizierungsmerkmale (z.B. Login-Name u. Passwort) und für eine Zwei-Faktor-Authentifizierung das Behördenkennzeichen (BhKnz) an den IAM-Service, der sie
Bitte vorherhige Version benutzen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Falls der IAM-Service die Auswertung des BhKnz nicht unterstützt, wird dieses Authentifizierungsmerkmal als optional gewertet.
Bitte vorherige Version benutzen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Das Interface `Security` stellt der Geschäftsanwendung die im Weiteren beschriebenen `Authentifizierungsmanager` und `Berechtigungsmanager` der Fachanwendung zur Verfügung.
Das letzte "Fachanwendung" ist zu viel.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die Methode `authentifiziere(applicationID)` im Authentifizierungsmanager liest diese Authentifizierungsdaten aus der betrieblichen Konfiguration und führt damit eine OAuth2.0-konforme Authentifizier
Bitte die Methodenaufrufe entsprechend der Abbildung https://github.com/IsyFact/isyfact-standards/blob/master/isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/security-schnittstellen.dn.svg beschreiben. 

Bitte dies für das gesamte Dokument prüfen.

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +NOTE: Das Behördenkennzeichen (BhKnz) kann derzeit für den Client-Credentials Flow noch nicht von isy-iam ausgewertet werden. Aus diesem Grund findet es keine Verwendung im Authentifizierungsmanager
BHKNZ

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Für den Transport von Benutzerinformationen, wie z.B. BhKnz, wird das Access-Token verwendet.
BHKNZ

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die folgende Abbildung zeigt die System-Architektur mit dem Webserver in der Nutzungsschicht und dem Anwendungskern vor der Anwendung und dem IAM-Service in der Logik- u. Verarbeitungszone.
Bitte zurücksetzen auf "Informations- u. Dienstezone".

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Als optional mögliche 2-Faktor-Authentifizierung ist im IAM-Service die Übermittlung und Auswertung des Behördenkennzeichens (BhKnz) vorgesehen.
BHKNZ

2023-09-13 09:39 UTC, dauna-msg commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die Implementierung des IAM-Service muss für die 2-Faktor-Authentifizierung dieses Feature unterstützen, andernfalls wird das BhKnz als optionales Attribut betrachtet.
BHKNZ

2023-09-14 12:15 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/images/konzept/security-schnittstellen.dn.svg
Done

2023-09-14 12:39 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die Implementierung des IAM-Service muss für die 2-Faktor-Authentifizierung dieses Feature unterstützen, andernfalls wird das BhKnz als optionales Attribut betrachtet.
Done

2023-09-14 12:40 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Als optional mögliche 2-Faktor-Authentifizierung ist im IAM-Service die Übermittlung und Auswertung des Behördenkennzeichens (BhKnz) vorgesehen.
Done

2023-09-14 12:42 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die folgende Abbildung zeigt die System-Architektur mit dem Webserver in der Nutzungsschicht und dem Anwendungskern vor der Anwendung und dem IAM-Service in der Logik- u. Verarbeitungszone.
Done

2023-09-14 12:45 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Für den Transport von Benutzerinformationen, wie z.B. BhKnz, wird das Access-Token verwendet.
Done

2023-09-14 12:51 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Das Interface `Security` stellt der Geschäftsanwendung die im Weiteren beschriebenen `Authentifizierungsmanager` und `Berechtigungsmanager` der Fachanwendung zur Verfügung.
Done

2023-09-14 12:52 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Falls der IAM-Service die Auswertung des BhKnz nicht unterstützt, wird dieses Authentifizierungsmerkmal als optional gewertet.
Done

2023-09-14 12:58 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Hierbei übermittelt der Benutzer seine Authentifizierungsmerkmale (z.B. Login-Name u. Passwort) und für eine Zwei-Faktor-Authentifizierung das Behördenkennzeichen (BhKnz) an den IAM-Service, der sie
Done

2023-09-14 12:59 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Die Authentifizierung und grobgranulare Autorisierung (mittels des Nutzers zugeordneten Rollen) erfolgt an den Außenschnittstellen der Systemlandschaft (Portal, Authentication-Gateway bzw. Service-
Done

2023-09-14 13:00 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Eine Zweifaktor-Authentifizierung ist durch das Behördenkennzeichen (BhKnz) als zusätzliches Authentifizierungsmerkmal konzipiert, allerdings setzt dies im IAM-Service voraus, dass dieses Merkmal d
Done

2023-09-14 13:01 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +* Innerhalb des Anwendungskerns eines IT-Systems wird das `JWT Access-Token` weitergegeben. Zur Stärkung der Vertrauenswürdigkeit wird jedes `JWT Access-Token` beim Eintritt in ein IT-System auf Gült
Done

2023-09-14 13:02 UTC, msg-ptavoul commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +NOTE: Das Behördenkennzeichen (BhKnz) kann derzeit für den Client-Credentials Flow noch nicht von isy-iam ausgewertet werden. Aus diesem Grund findet es keine Verwendung im Authentifizierungsmanager
Done

2023-09-14 14:40 UTC, kollmana commented on isyfact-standards-doc/src/docs/antora/modules/isy-security/pages/konzept/inhalt.adoc
> +Die Methode `authentifiziere(applicationID)` im Authentifizierungsmanager liest diese Authentifizierungsdaten aus der betrieblichen Konfiguration und führt damit eine OAuth2.0-konforme Authentifizier
Ist mit merge von IFS-2483: Überarbeitung der Schnittstellen des Moduls ‚Security‘ geschehen.

2023-10-09 09:30 UTC, dauna-msg approved these changes

2023-10-09 09:31 UTC, merged