ISY-219: migration guide isy-security - document annotation for user authentication
IsyFact/isyfact-standards pull request #93
Opened 2023-09-13 10:44 UTC by tbribram

Depends on #66

2023-09-22 13:00 UTC, huebnercl requested changes

2023-09-22 13:00 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The properties `username` and `password` are only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects the _authentication properties_ on a dedicated path. This means the previous defined properties `username` and `password` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get these values as parameters through external application invocations. In these cases _isy-security_ will transfer the _authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.username`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `username`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-22 13:00 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The properties `username` and `password` are only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects the _authentication properties_ on a dedicated path. This means the previous defined properties `username` and `password` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get these values as parameters through external application invocations. In these cases _isy-security_ will transfer the _authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.password`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `password`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-22 13:00 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
The property `bhknz` is only defined for **Confidential Clients** independent on _isy-sicherheit_ or _isy-security_. But with _isy-security_ the configuration of a _spring conform ClientRegistration_ is introduced, which expects this _properties_ on a dedicated path. This means the previous defined property `bhknz` of _batch-_ or _task_-configurations, have to be shifted to the new property-location. This mechanism will only be used by the `Security`-Interfacemethod `authentifizieren`.

All other `Security`-Interfacemethods will get this value through external application invocations out of a _client-certificate_ transfered in the HTTP-Header. In these cases _isy-security_ will transfer the _2FA-authentification data_ in the internal `SecurityContext` analog to the `AufrufKontext` in _isy-sicherheit_.

```suggestion
|-|`isy.security.oauth2.registration.<registration-id>.password`| für _ConfidentialClient_-Konfiguration der geänderte Pfad für Property `bhknz`, mit _isy-security_ nun innerhalb einer _Spring konformen ClientRegistration_
```

2023-09-22 13:00 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
>  === Sicherheit
The subchapters of chapter `Bausteine` have a confusing order.
Suggestion in alphabetic order:
== Bausteine
=== Batchrahmen
=== Task Scheduler
=== Service
=== Sicherheit

2023-09-28 09:14 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
Actually part of #66

2023-09-28 09:14 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
Actually part of #66

2023-09-28 09:14 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
Actually part of #66

2023-09-28 09:17 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
>  === Sicherheit
While not related to the changes in this PR I agree that the ordering can be improved. Although I would put the "Sicherheit" chapter at the beginning since the other chapters depend on the changed security configuration.

2023-09-28 09:30 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
>  === Sicherheit
As you already mentioned the order in tickets that actually add content to those chapters (https://github.com/IsyFact/isyfact-standards/pull/43#discussion_r1334376874) I'd prefer changing the order in those tickets.

2023-10-05 14:22 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
>  === Sicherheit
we could shift the reordering in a following ticket as soon as all chapter dependent changes were merged together. I think the reordering will be more easier in a completted document than in the current branch depending and splitted files.

2023-10-05 14:22 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
that's ok, but is still not part there.

2023-10-05 14:24 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
that's ok, but is still not part there.

2023-10-05 14:31 UTC, tbribram commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
I commented my thoughts on the suggested change in https://github.com/IsyFact/isyfact-standards/pull/66#discussion_r1339775896 and revised the incorrect with a correction description of how these properties replace old configuration https://github.com/IsyFact/isyfact-standards/pull/66/commits/a4345fbf3cd96465e57574e3cae67f1f2edb2853#diff-d136f0f6a2e2f2937af2b782713b8d34cd1e90ac9a61caaa2f5b0f09ff57555dR54-R56.
How exactly these replace the old configuration depends on the individual application since it wasn't part of the old security component. How this impacts other parts of isyfact-standards like isy-batch and isy-task—which had semi-standardized configuration—should be described in their respective migration guides.

2023-10-05 15:35 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
that's ok, but is still not part there. Add it there as suggestion.

2023-10-05 15:37 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
>  === Sicherheit
we could shift the reordering in a following ticket as soon as all chapter dependent changes were merged together. I think the reordering will be more easier in a completted document than in the current branch depending and splitted files.

2023-10-06 09:33 UTC, huebnercl approved these changes, later dismissed
approved with a small suggestion for the changed.log and with the sureness the open conversations are solved in https://github.com/IsyFact/isyfact-standards/pull/66

2023-10-06 09:33 UTC, huebnercl commented on CHANGELOG.md
> +  * `ISY-219`: Abschnitt zur Migration der Annotation @NutzerAuthentifizierung
```suggestion
- `ISY-219`: [isyfact-standards-doc] Migrationsleitfaden zur Umstellung auf isy-security
  * Abschnitt zur Migration der Annotation @NutzerAuthentifizierung
```

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
when i think about the requirements for this description, it should contain information for an admin or devop, who have to migrate an existing configuration to the new spring _client registration_ configuration or for a person who is total new in the usage of isyfact. 
Both needs information about the meaning of this property and its usage in isyfact 3.0. 
There is no need about details what happened with it in previous isyfact versions in conjunction with the `Aufrufkontext`, which still not exist in isyfact 3.0 anymore (ok it is temporary referred for downward compatible requests, but it will not play any important role to be mentioned in the description here)

the property `username`, independent which prefix it have, will define the name of the user of a _confidential client_, which will be used for authentication by the iam-service.
And with isyfact 3.0 and the introduction of a _spring client registration_ configuration for each user, the reader of this document needs information, which value he has to define for this property, either shifting from an old configuration with an other prefix or inserting as new value.

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
please see comment above about `username`

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
please see comment above about `username`

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.username`|neu, wurde vorher aus dem AufrufKontext ausgelesen
solved in https://github.com/IsyFact/isyfact-standards/pull/66

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.password`|neu, wurde vorher aus dem AufrufKontext ausgelesen
solved in https://github.com/IsyFact/isyfact-standards/pull/66

2023-10-06 09:33 UTC, huebnercl commented on isyfact-standards-doc/src/docs/antora/modules/changelog/pages/migrationsleitfaden.adoc
> +|-|`isy.security.oauth2.registration.<registration-id>.bhknz`|neu, wurde vorher aus dem AufrufKontext ausgelesen
solved in https://github.com/IsyFact/isyfact-standards/pull/66

2023-10-09 07:30 UTC, dauna-msg approved these changes

2023-10-09 07:30 UTC, merged